### ISSUE TITLE
Smooth chat experience

### ISSUE THREAD

**Issue by ricardosaavedra** [status-im/ideas#100]
## Preamble

    Idea: UX 100
    Title: Smooth chat UX
    Status: Draft
    Created: date created on 2018-03-23

## Summary

The main goal of this UX swarm is to "smooth the edges" of our chat experience for our upcoming launch. Our current chat implementation works, but it is still not optimal. Two of the core OKR's (Use Status every day and message is reliable) depends heavily on a good and smooth chat experience.

The UX issues are split between 3 groups, starting with the low effort tasks/high payoff moving to big effort/high payoff (v1, v2, v3). Although its scope can seem ambitious at first, the idea is to have deliverables once in two weeks. Those deliverables will contain all the necessary documentation necessary for implementation. More designers are welcome to join as we go, as well as developers, QA's PM's.

## Swarm Participants

- Lead Contributor: @ricardosaavedra
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- PM: 
- UX (if relevant): 

## Workflow and day-to-day activities

Every beginning of a new cycle (you can call it sprint if you'd like), we will decide together what to focus on for the upcoming two weeks as well as discussing current problems, technical challenges and the best solutions (trade-off between implementation cost and UX).
As ideas and design solutions start to emerge, we will get together to validate/critique the proposed solutions until we arrive at a group consensus.

### Product Description

**V1 - quick fixes**
- Chat view / message status
- Chat view / last seen 
- Chat view / user page 
- Chat view / minior UI fixes 
- Chat view / message space optimization
- Chat view / timestamps
- Chat view / adding/blocking new contact flow
- Keyboard / use cases behaviors
- Keyboard / maximum message width
- Keyboard / fixing console position
- Offline states and error handling 

**V2 - group chat improvements**

- Group chat view / chat metadata
- Group chat view / message space optimization 
- Group chat / timestamps
- Group chat / seen by logic and documentation
- Group chat / grouping messages 
- Group chat view / top bar behavior

**V3 - more engaging and visually clear home screen**

- Home screen / starting a new chat flow
- Home screen / visual consistency fixes
- Home screen / search function 
- Home screen / loading messages experience

For more details about each one of those fixes, please visit: https://docs.google.com/document/d/1AyU9mWMG1MxNPPBr1kidIl7eMJzPhbUjJjUNBBxZpg8/edit

### Team & Dependencies

Ideally, we would have at least 2 developers (Whisper, Clojure) in the team acting as a stakeholder in the process.

Even though you won't be implementing those designs directly, you should act as if you were, so that what comes out of this process isn't a wishfull thinking of our collective imagination; bearing no relationship with reality (time constraints and limited resources). 

Goal Date:  

### UX swarm, what's new: 

The idea behind the UX swarm to be able to work on the solutions (together) ahead of time; compared to how swarms have been working in the past. With this initiative we wish to achieve:

- transparency about UX process; everyone is involved and welcome to join at any point
- more collaboration between developers and designers 
- be able to outsource some of the work (more bounties)
- more time to fail, and try different solutions
- better documentation and chance to validate assumptions (user testing)

## Dates
Goal Date:   

Description: 

Testing Days required: 

## Success Metrics

- average of 10 messages a day by each active user 
- messaging experience feels good: 90% of surveyed users feel like the messaging experience is solid enough compared to new apps
- 80% of users that installed the app used the messaging feature in their first week (simple and inviting)

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by ricardosaavedra** [comment]
Swarm update 
![error handling](https://user-images.githubusercontent.com/182161/38079924-1b03bc6e-337b-11e8-82d0-107cf2010ad8.png)
![group chat headers](https://user-images.githubusercontent.com/182161/38079925-1b43fb4e-337b-11e8-9854-b17ac6d2072e.png)
![last seen use cases](https://user-images.githubusercontent.com/182161/38079927-1b7a24e4-337b-11e8-9f09-28419dce29a5.png)
![sending message](https://user-images.githubusercontent.com/182161/38079928-1ba9030e-337b-11e8-8d8c-d9f3e6909dd5.png)
![space group chat](https://user-images.githubusercontent.com/182161/38079929-1bde4bd6-337b-11e8-8f54-7a4bb9282b33.png)
![space optimization 1-1](https://user-images.githubusercontent.com/182161/38079932-1c1b1656-337b-11e8-962a-2c31cdb6a32f.png)
![space optimization group chat](https://user-images.githubusercontent.com/182161/38079933-1c460d3e-337b-11e8-81ca-b94717be8bb7.png)
![user contact update](https://user-images.githubusercontent.com/182161/38079934-1c72151e-337b-11e8-9378-28b10cbaba18.png)
![space optimization group chat](https://user-images.githubusercontent.com/182161/38079968-2c61e346-337b-11e8-9339-3b0c95e1cbcd.png)
![user contact update](https://user-images.githubusercontent.com/182161/38079969-2c92f792-337b-11e8-86af-9243e709ae37.png)

**Comment by nikitalukianov** [comment]
![chat_new_screens](https://user-images.githubusercontent.com/33906272/38136070-aa622310-3424-11e8-9cad-d394bc9f4c78.png)
![messages_states_all](https://user-images.githubusercontent.com/33906272/38136077-b1c9038a-3424-11e8-8183-463d4e5a4000.png)
![new_size_of_messages](https://user-images.githubusercontent.com/33906272/38136080-b635073e-3424-11e8-8faf-43628cd10702.png)

**Comment by nikitalukianov** [comment]
![chat_new_screens](https://user-images.githubusercontent.com/33906272/38152373-2511340c-3470-11e8-8d04-7d374c48f69b.png)
![messages_states_all](https://user-images.githubusercontent.com/33906272/38152377-292e7194-3470-11e8-914f-7f52a461a5af.png)

**Comment by annadanchenko** [comment]
@nikitalukianov  Can you provide the design for the long sum in transaction message, please? On the sample there is 0.02094 ETH, but sum can have any number of digits before comma and 18 digits after comma, for example 123.1234567890123456789 ETH. I guess we also need to have 1 common rule for the long sum (do we show the exact sum, round it or add dots after some number)

**Comment by nikitalukianov** [comment]
@annadanchenko good point, I'll make this in update, agree about 1 common rule

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
