### ISSUE TITLE
Extensions

### ISSUE THREAD

**Issue by jeluard** [status-im/ideas#101]
## Preamble

    Idea: 101
    Title: Status extensions
    Status: Draft
    Created: 2018-03-26

## Summary

A set of extension points (including chatbots) so that external developers can enhance status

## Swarm Participants

- Lead Contributor: @jeluard
- Testing & Evaluation: ??
- Contributor: ??
- PM: @andytudhope
- UX: @denis-sharypin

## Product overview

As an ecosystem status needs to offer extension capacities so that external developers can develop on top of it.
This swarm will review the current state of our extensions, specify a updated mechanism based on our current knowledge and eventually implement it.

### Product Description

3rd party developers will have access to API and documentation allowing them to extend status via various hooks using a simple API.
There won't be any distinction between those extensions and status itself (it will feel native).

### Requirements & Dependencies

None

### Minimum Viable Product

* document existing working features offered by chatbots (as documented [here](https://docs.status.im/))
* list (potential) new types of extensions
* prepare new workflow / mockups (special care for chatbots)
* prepare draft specifications detailing technical solution to be discussed with team (development, distribution, incentivization)
* detail how to integrate with status API / screens

During definitions of specifications a number of potential use cases must be considered, namely:

* retrofit existing chat commands
* ethereum standards (721, ..)
* winners from status [hackathon](https://blog.status.im/announcing-winners-of-the-status-global-hackathon-a44fb54e98f7) ([favor network](https://github.com/status-im/hackathon/issues/140))
* video sharing technologies ([livepeer](https://livepeer.org/))
* token transfers (https://raiden.network/)
* https://ethlend.io/en/, https://trustlines.network/, ...
* consider the [feedback](https://github.com/status-im/status-react/wiki/Hackathon-Feedback) we got from our first hackathon
* extensions mechanisms of other chat applications

Note that idea #96 might be the first guinea pig of extensions.

Goal Date: 3 weeks after beginning

## Dates

Iterations will be defined based on specification and team feedback.

## Success Metrics

- 2 internal extensions shipped 
- 3 external extensions shipped
- quality of documentation recognized: few support request related to extensions

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by andytudhope** [comment]
I am happy to dedicate 30hrs a week to this. It will mean my involvement in Open Bounty needs to be decreased a bit, but I really, really want to see this happen.

**Comment by martinklepsch** [comment]
One thing that seems at least superficially interesting to me is the ability to "suggest" a transaction to an address. In a sense it's like a "receive request" but it could be done for more complex transactions (like bounty funding, payout, etc.) too maybe? Primarily thinking of this in the context of a machine suggesting a transaction based on some previous user action. (some related slack conversations: [one](https://status-im.slack.com/archives/C8QP8S5UH/p1521486532000284) & [two](https://status-im.slack.com/archives/C5Z5NRYKS/p1520743988000038))

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
