### ISSUE TITLE
Decentralized development direction

### ISSUE THREAD

**Issue by feuGeneA** [status-im/ideas#116]
## Preamble

    Idea: 116
    Title: Decentralized development direction
    Status: Draft
    Created: 2018-03-28

## Summary

*SNT holders pledge SNT in order to decide the direction of Status development, just like core contributors pledge hours.*

Status Open Bounty is off to a great start in enabling organizations to decentralize their development.  But what about the direction of that development?

Including non-technical users in the SOB ecosystem could decentralize product management just like existing SOB functionality can decentralize software development.  It would empower the broader community to have their say, to put their money where their mouth is, and to develop a real sense of association with the product and the ecosystem.

And, while the Status Open Bounty fund is a great jump start, having development funding come from users seems the ultimate in sustainability for the ecosystem as a whole.
 
## Swarm Participants

- Lead Contributor: @feuGeneA
- Testing & Evaluation: TBD
- Contributor:  TBD
- Contributor: TBD
- PM: TBD
- UX (if relevant): TBD

## Product Overview

With regard to sustainability, due to the $1m bounty fund there's obviously no financial need to draw money from the community, at least not in the foreseeable future.  However there are non-financial short term needs that this idea would help fulfill: the need to instill more utility in the Status Network Token (SNT), the need to build a more involved community, and the need to lighten the burden on the Status org of the not-insignificant task of generating a steady supply of bounties.  As for tong term sustainability, when the bounty fund runs out, in 5 or 50 years, a decentralized development direction process could enable continued development in perpetuity.

What's missing from https://openbounty.status.im is a "For users" section.  There's "For Developers," and "For Organizations," but there's no outlet for non-technical users to get involved.  Just as developers can hunt bounties, users should be able to offer them.

[Draft comment: There is the section on openbounty.status.im, "Get the community to fund your ideas," but it's addressed to "developers on GitHub," which likely dissuades anyone non-technical.  Also, it says "you can easily pitch/request funding."  Are those functionalities developed yet? I couldn't find anything through the SOB site/login.]

This proposal is to implement SOB use cases for non-technical people to get involved with making the decisions about what gets funded and therefore what gets developed.

### Product Description

First and foremost:
* As an SNT holder, I want to fund an existing bounty.  [Draft note: This already works, in that anyone can send funds to a bounty's contract address, right? In which case the only thing to "do" here is explicitly communicate that this is a good channel for user participation.]

Also at the fore, users may be wary of contributing before completion, especially for Issues that are still in a Draft status.  Therefore:
* As an SNT holder, I want to pledge some of my SNT as a reward for the implementation of a bounty, but I do not want to release funds from my wallet to the bounty contract until (unless) the idea is actually implemented.  [How does the SOB contract work now?  A method to reclaim funds from stale bounties *may* obviate this user story.]

Lastly of the fore, enable user created bounties:
* As an SNT holder, I want to create a bounty on an Issue that does not already have one, in order to help incentivize completion of an idea that I value personally.

A more specific/refined case of the prior user stories, given the fact that we use github.com/status-im/ideas as our primary means of development direction:
* *As an SNT holder, I want to pledge SNT to a status-im/ideas Issue, just as core contributors pledge hours.*

Also enable user created Issues:
* As a non-core community member, I want to create a new Issue in status-im/ideas, for which I will create an initial bounty.  [Draft note: Are GitHub users that are not members of the Status org already permitted to create Issues in status-im/ideas?  If so, then explicitly communicate that this is a good channel for user participation constitutes "done."]

And finally, communicate these use cases:
* As a Status user, I want http://openbounty.status.im/ to show me how I can get involved with directing development of Status.

And there is plenty of room for creativity with related use cases.  For example:
* As a pledger, I want to offer a matching pledge, in order to encourage more pledging, in order to leverage my funding.  (The SOB fund itself could be leveraged in this way.)
* As an idea creator, I want to be rewarded for my good ideas, with the reward paid from a bounty fund dedicated specifically to new ideas, a fund to which anyone can contribute.  (Perhaps reward is paid upon acceptance of the idea by core, or perhaps upon completion of the swarm, and perhaps it's magnified by the number of people who voted up or pledged for the idea.)  [Draft note: I heard Ana suggest to someone that they could claim a bounty by reporting a bug, which would be an instance of this general case.]

### Requirements & Dependencies

Currently, ["deploying a bounty contract costs gas and currently we deploy those contracts,"](https://status-im.slack.com/archives/C9XUUJVV2/p1522327554000276) and ["the flow/UX isn’t in a place where we could easily move to users signing those transactions/paying the gas themselves."](https://status-im.slack.com/archives/C9XUUJVV2/p1522327600000286)

### Minimum Viable Product

(Recapped from Product Description)
* As an SNT holder, I want to fund an existing bounty.
* As an SNT holder, I want to create a bounty on an Issue that does not already have one, in order to help incentivize completion of an idea that I value personally.
* As a non-core community member, I want to create a new Issue in status-im/ideas, for which I will create an initial bounty.
* As a Status user, I want http://openbounty.status.im/ to show me how I can get involved with directing development of Status.

## Dates
TBD

  

 

 

## Success Metrics

* Number of user-funded bounties.
* Number of user-initiated bounties.
* Number of user-created Issues funded and completed.
* Number of users driving through the newly created "For Users" section of openbounty.status.im.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
