### ISSUE TITLE
Status Desktop (Electron)

### ISSUE THREAD

**Issue by flexsurfer** [status-im/ideas#12]
## Preamble

    Idea: DEV#12
    Title: Status Desktop (Electron)
    Status: WIP 
    Created: 2017-11-13
    Requires #2, #7, #9 

## Summary
Develop Status Desktop application for Mac, Windows, and Linux using Electron (formerly known as Atom Shell, is an open-source framework developed by GitHub)

## Vision
We are already working on Status Desktop components, implementing React Native components and libraries using Qt technology, but this work requires a lot of resources. Using Electron and React Native Web library we can develop Status Desktop reusing our code base from status-react without a lot of modifications and this work requires only clojure developers resources for code development.

## Swarm Participants

- Lead Contributor: @flexsurfer
- Testing & Evaluation: @flexsurfer
- Clojure Contributor: @yenda
- Clojure Contributor: @goranjovic 
- Go Contributor: @adambabik
- Go Contributor: @divan
- UX: @denis-sharypin

## Requirements

Status Desktop should provide for users all the functionality that is available in the mobile application

### Minimum Viable Product

Goal Date: 2017-12-12
Description: 
1. Account can be created or recovered
2. User can login
3. New contacts can be added
4. Users can send 1-1 messages to each other
5. Users can join public chats and send messages

### Iteration 1..N
Goal Date:  
Description: 
1. Users can create public groups or join public chats and send messages
2. Users can add reaction to messages
...

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by flexsurfer** [comment]
Idea repository - https://github.com/status-im/status-electron

**Comment by flexsurfer** [comment]
We have working prototype for macos, it's possible to send whisper messages between desktop and mobile

Next steps:
Work on nix and win builds

and Implement next :
1) Implement app-db
2) Save and read app-db as edn file
3) Login screen
4) New contact screen
5) Chats

**Comment by flexsurfer** [comment]
FAQ:
1. Why is status-electron code not in status-react repo
To do not distract clojure team, later status-electron should be merged into status-react
2. Why can't we reuse status-react views
Because status-react views not pure, we have subscriptions and i18l labels, to reuse we should make it pure, move labels and subscriptions outside the view function

**Comment by flexsurfer** [comment]
First release https://github.com/status-im/status-electron/releases

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
