### ISSUE TITLE
Discoverable public chats

### ISSUE THREAD

**Issue by goranjovic** [status-im/ideas#13]
## Preamble

    Idea: DEV#00
    Title: Public chat discoveries
    Status:  WIP 
    Created: 2017-11-13
    Requires: #8 

## Summary

Allow public chats to be discoverable so that people can join them.

## Vision

Where we are at the moment:

- All public chats can be joined if the user knows their exact name/identifier
- But they are not discoverable - instead the public chats are hardcoded in Discover screen: status, ethnews, ethereum and devcon.
- In addition, there is a number of open issues and bugs with regards to public chat functionality (to-do add links to issues)

Where we want to be:
- Public chats are discoverable and ranked according to their popularity 
- Users can see the number of participants in discovered public chats (allowing for some latency)
- Public chats are reasonably bug free

## Swarm Participants

- Lead Contributor: @goranjovic
- Testing & Evaluation: TBD
- Contributor: TBD
- Contributor: TBD

## Requirements

- Every app node needs to broadcast a list of all public chats currently open on that account to all its contacts.
- Those contacts will broadcast its own open public chats and any other chats they received.
- All public chat discoveries are stored in local database with public key as the primary key and a string array as the list of public chat identifiers.
- Then those public chat discoveries can be aggregated by public chat identifiers and we can have a list of most popular public chats by number of participants.

## Goals & Implementation Plan

It is recommended that #8 is implemented before this Idea, so that Discover is in a consistent state before we add any new feature.

### Minimum Viable Product

TBD

Goal Date: TBD
Description: TBD

### Iteration 1
Goal Date: iteration sign off + 2 weeks
Description: Discoverable public chats

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by naghdy** [comment]
Closing this as is hasn't been touched/tackled since it was first created. We can look through for ideas when we tackle groups chats next.
