### ISSUE TITLE
Status-go SDK

### ISSUE THREAD

**Issue by adriacidre** [status-im/ideas#131]
## Preamble

    Idea: <to be assigned>
    Title: Status GO-SDK
    Status: Draft
    Created: 2018-04-03

## Summary

Provide an easy to use GO-SDK library to allow community developers easily interact with status messaging.

## Swarm Participants
- Lead Contributor: @adriacidre
- Testing & Evaluation: 
- Contributor:
- Contributor:
- PM:
- UX (if relevant):

### Product Description

One of the main goals of status is to grow its community, however is not easy to work on status-go project as a community developer. 
Is not easy to set up an environment

- Identify where to start
- Interact with status messaging system.
- Test your changes

The idea behind this swarm is to simplify this by allowing community developers to interact with status, based uniquely on status-go library.

### Requirements & Dependencies

- *Easy to use SDK* : Using a sdk should be as easy as using any other messaging system, allowing you to subscribe or publish to specific chats.
- *The less dependencies the better* : ATM and in order to interact with status messaging system we need to interact with code on status-go and status-react repos. This should be simplified to allow devs work only on top of status-go
- *Quick dev environment setup* : Following the previous point, if we’re only based on status-go, dev environment should be trivial. Should be easy to build apps and distribute them as binaries for different platforms.

### Minimum Viable Product

MVP should allow a developer to accomplish some minimal actions:

- Connect : creates a new connection
- Close : closes active connection
- Auth : login as a specific user
- Subscribe : subscribe to a channel
- Unsubscribe : unsubscribe from a channel
- Publish : send a message.

_All methods should work for 1to1, groups and public chats._

With this methods building a simple `autoresponder bot` should be as simple as:

**TO BE DEFINED**
```go

// Connect to the default status url and defer closing the connection 
st, _ := status.Connect(st.DefaultAddr) // -> localhost:51515
defer st.Close()

// Authenticate as an specific user
st, _ = status.Auth([]byte(“S3cretT0ken”))

// Subscribes to any message on chat chatID
sub, _ := st.Subscribe("chatID", func(m *st.Msg) {
    // Replies the received message
    m.Reply([]byte("I can help!”))
    sub.Unsubscribe()
})

// Simple message publisher
st.Publish(“buddy_token", []byte("Hello World"))

```

SDK should be provided with different, easy to follow and well documented examples _(TBD)_:

- Autoresponder bot (nice for testing)
- Google assistant integration
- Slack proxy (use status from slack)
- Reminders (set and get reminders)

Description: 

### Useful links & Dependencies
https://github.com/mandrigin/status-go-bots — http://offsite.chat and #humans-need-not-apply bots.

### Blockers
New Status App communication protocol - https://github.com/status-im/ideas/issues/87

## Dates
Goal Date: TBD

Description: TBD

Testing Days required: TBD

## Success Metrics
TBD

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by mandrigin** [comment]
Just to mention: https://github.com/mandrigin/status-go-bots
It has the following API:
```go
user := SignupOrLogin(nodeManager, conf.Password())
channel = user.Join(conf.Channel, conf.Nickname)
channel.RepeatEvery(10 * time.Second, func(ch *bots.StatusChannel) {
	message := fmt.Sprintf("Gopher, gopher: %d", time.Now().Unix())
	ch.SendMessage(message)
})
```

and some a "Quickstart" method if you want standard command-line switches, etc

**Comment by lukaszfryc** [comment]
@adriacidre since I want to learn basics of _go_, I can help you with reviewing the SDK docs and then trying to use it in practise by creating a simple bot. This can give you an idea how easy it is to get started with the SDK.

**Comment by adriacidre** [comment]
awesome @lukaszfryc! I'll keep you updated :)

**Comment by adriacidre** [comment]
Hey, @lukaszfryc.

1.- You're right! The idea is to fully support all types of messaging present on the app. 
About send, request ETH, should be theoretically possible to implement send, request ETH commands, not sure if that can be part of first iteration, but definitely something we can consider

2.- I was discussing with @mandrigin about this and he said `please, sync that with the test team too. they are interested in the bots like that. we are starting to use my implementation for #091-extended-e2e-test, but later on we can switch to the result of this idea.`

Maybe you could prepare a prioritized list of features you'll like to see so they can be delivered on small iterations.

**Comment by arnetheduck** [comment]
Fantastic, this answers one of the first questions when I started looking at status from a dev's point of view, and indeed a question I got from a dapp developer during the fossasia conference, that I didn't know how to answer (ie how do I make my app status-compatible).. is there any overlap between this idea and https://github.com/status-im/ideas/pull/133?

**Comment by adriacidre** [comment]
hey @arnetheduck 

I've been discussing with @jeluard  about overlapping with #133 , and we arrived at the conclusion both have different purposes. This is his input:

```
My idea is more around extending status. With access to internal APIs and UI system.
So there is an overlapp in the sense we could interact with messaging system but from within the app.
So I think both have different purposes
```

As he says the overlapping will happen having `status messaging protocol` implemented on status-go and status-react. However, if the plan is to grow the community, the more languages implementing the protocol the the better.

**Comment by lukaszfryc** [comment]
@adriacidre I'm thinking about the bot / tool in 2 ways. First, we need bots that could send messages periodically to different types of chats. Secondly, we need a more general tool (CLI?) that could be used to generate messages.

### Test Bot requirements

1. Bot for the public chat that would send messages every `x` seconds 
This is already done by the "pinger" bot in https://github.com/mandrigin/status-go-bots 👍 

2. Bot for the group chat that would send messages every `x` seconds 

3. Bot for the 1-1 chat that would send messages every `x` seconds 
 
4. Bot for all types of chats that would only reply to messages

5. Extend the bot functionality to send `/send` and `/request` messages / commands

### CLI tool requirements

Ordered from most to least important:

1. Ability to send "n" number of messages to 1-1 chat, public chat, group chat
I'd like to run it with `--message-count=100` to send 100 messages to a chat. Also `--message-content="Hello!"` would send the "Hello!" message. 
Apart from the data generation I imagine this to be used to test incoming notifications. We would put the app into background and use the tool to send a message to 1-1 chat that would trigger a notification on the device.

2. Ability to use `/send` and `/request` commands
I'd like to run it with `--command=send` or `--command=request`, `--params="0.03" parameters that would generate `/send`, `/request` messages with "0.03" ETH the same way it happens in the app.

3. Ability to send tokens (transactions)
I'd like to just send tokens. Just a simple transaction, same way as we do in Wallet. 

4. Ability to create a new account on blockchain
I'd like to create a new account that could be later populated by messages and used by UI tests to log in.

**Comment by lukaszfryc** [comment]
cc @yevh-berdnyk @mandrigin

**Comment by adriacidre** [comment]
Hey @lukaszfryc, so, SDK is the library both `bots` and `cli` will use to interact with status. That said, should be easy to build any `cli` or `bot` with your specifications (once we have the SDK), for eample 1st bot `Bot for the public chat that would send messages every x seconds` should look something like:

```main.go
import "github.com/status-im/status-go/sdk"

func main() {
	// Connect to the default status url and defer closing the connection 
	st, _ := status.Connect("localhost:51515")
	defer st.Close()

	// Authenticate as an specific user
	st, _ = status.Auth([]byte(“S3cretT0ken”))

	st.Publish("channel", []byte("Hello World"))
}
```

this will get compiled on a binary `./hello`, so you can call it with `./hello`. This will only send 1 message, and you can then manage scheduling with a cronjob or with a more elaborated solution. 

Anyway all this will be something to be built on top of the SDK and not part of it.

**Comment by lukaszfryc** [comment]
Sounds great @adriacidre. Looking forward to playing with it!

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.

**Comment by adriacidre** [comment]
Related PR: https://github.com/status-im/ideas/pull/149
