### ISSUE TITLE
DApp Catalog

### ISSUE THREAD

**Issue by goranjovic** [status-im/ideas#14]
## Preamble

    Idea: DEV#00
    Title: DApp catalog
    Status:  WIP 
    Created: 2017-11-13
    Requires: #8

## Summary

Add support for discoverable dapps.

## Vision

Where we are at the moment:

- Dapp discoveries are hardcoded to a small list of dapps selected by hand by developers: Dentacoin, Melonport, Augur, Ethlance, bchat and Oaken Water Meter.
- The same dapps are included in the list of initial contacts (also hardcoded in the app)

Where we want to be:
- Dapp creators can publish dapps in a way that doesn't involve embedding the dapp details and URL within the Status code, e.g. in a PR
- Newly added dapps are discoverable by the users as they appear
- The list of dapps is curated by admins to ensure they conform with the quality standards criteria for inclusion
- Admins also need to be able to remove a dapp in case that inclusion criteria are no longer met
- Important constraint: dapp addition, curation and discoverability need to be completely decentralized - there mustn't be any dependence on any central servers, services or persons.

## Swarm Participants

- Lead Contributor: TBD
- Testing & Evaluation: TBD
- Smart-Contracts: @3esmit
- Contributor: TBD

## Requirements

TBD

## Goals & Implementation Plan

It is recommended that #8 is implemented before this Idea, so that Discover is in a consistent state before we add any new feature.

### Minimum Viable Product

TBD

Goal Date: TBD
Description: TBD

### Iteration 1
Goal Date: TBD
Description: Discoverable dapps

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by 3esmit** [comment]
Suggestions: 
1. curation is democratically voted by SGT in StatusNetwork Alpha stage, and SNT for StatusNetwork > beta;
2. votes use delegation democracy as #20;
3. system works in a simmilar concept as #18.

**Comment by naghdy** [comment]
Closing as this idea hasn't been touched since it was created
