### ISSUE TITLE
Requirements for a High-Quality Group Chat

### ISSUE THREAD

**Issue by themue** [status-im/ideas#15]
## Preamble

    Idea: PROC#015
    Title: Requirements for a High-Quality Group Chat
    Status: Draft
    Created: 2017-11-13
    Requires: https://github.com/status-im/ideas/issues/6

## Summary

To make Status strong in group chatting wie have to gather ideas and requirements
and compare them to our competitors.

## Vision

The group chat situation of Status is a bit messy. We used Slack for our internal
talks as well as for the community. Due to troubles with scammers we tried to use
Riot, which sadly misses features we're familiar with. So right now we use Slack
internally, Riot for the community, and Telegram for discussions about cryptocurrencies
and trading.

Our Status itself provides group chat features too. To create a powerful competitor
to existing products, not only Slack or Riot, we need to gather and prioritize
ideas and requirements for our software.

Additionally we have to compare our vision as well as the gathered set of ideas and
requirements with other tools on the market: Slack, Riot, WeChat, WhatsApp, Facebook
Messenger, Snapchat, and more. Goal is to compile a list of requirements to make Status
stronger than the market.

## Swarm Participants

- Lead Contributor: @themue
- Testing & Evaluation: (tbd)
- Contributor: Owner
- Contributor: Product Owner
- Contributor: (tbd)

## Requirements

- Establish infrastructure in Git or different tool to collect, discuss, and prioritize
  the ideas and requirements.
- In iterations:
  - Collect, discuss, and prioritize ideas and requirements.
  - Compare collected requirements to competitors.
  - Review requirements based on comparison.

### Minimum Viable Product

Goal Date: 2017-12-01
Description: Establishing of infrastructure and initial iteration.

### Iteration 2..N

Description: Continuous process to improve our product.

## Supporting Role Communication

(tbd)

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by themue** [comment]
- Idea https://github.com/status-im/ideas/issues/39 will be one source of requirements.
- Document for requirements gathering: https://docs.google.com/a/status.im/spreadsheets/d/1WLpL1ONczcbW7dcLFrTtjLVV4S62_x-zTRNUZBE0Z-o/edit?usp=sharing

**Comment by naghdy** [comment]
Closing this as its gone stale. We can use some of the ideas for when we tackle public group chats in the future.
