### ISSUE TITLE
Ideas should be three digits

### ISSUE THREAD

**Issue by oskarth** [status-im/ideas#158]
Currently idea numbers are in 1..3 digits. Ensure they are always in three digits, including filenames, README, links etc.

Example: 1-offline-inboxing => 001-offline-inboxing

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xba667ce09bab72c5e5fe85ebc73a32685d157bfcf98d3b7eea07cedba6da190a](https://etherscan.io/tx/0xba667ce09bab72c5e5fe85ebc73a32685d157bfcf98d3b7eea07cedba6da190a)

**Comment by debragail** [comment]
should this be a separate column in the table as well to separate it from the string in the idea column?  This would create a more elegant solution for the sorting issue.

**Comment by debragail** [comment]
I thought someone else solved this but I'll go ahead and send my PR because this is part of another bug I'm working on
