### ISSUE TITLE
Status fiddle (online editor for developing UI)

### ISSUE THREAD

**Issue by flexsurfer** [status-im/ideas#16]
## Preamble

    Idea: DEV#16
    Title: Status fiddle (UI online editor)
    Status: WIP
    Created: 2017-11-14

## Summary
UI editor in the web (something like fiddle.status.im) for creating status UI in "live" mode, so user can write code for UI and see the result immediately

## Vision
We're developing UI for status in 3 steps, 1 - designer prepares UI in vector editor and publishes it in Zeplin, 2 - developer implements UI from Zeplin in code, 3 - design review, could take a lot of time and resources for both designers and developers. We can seriously improve this process if designers provide UI in code to developers, but we need a simple way, tools for designers to do that.
Also, if we'll have such a tool, external contributors could develop UI for status without building and running status environment. And chatbot developers could test their bot suggestions UI.

**Update1**: And we could generate views in different sizes and look how app will look on different devices
Also we could generate views with different labels size to see how it may look with different languages, now we only check English version.

## Swarm Participants

- Lead Contributor: @flexsurfer
- Testing & Evaluation: 
- Contributor: 
- Contributor: 

## Requirements

It should be possible to open web page, type hiccup data structures and see resulting UI
And probably tutorials and templates for status UI.

### Minimum Viable Product

Goal Date: 2018-01-01
Description:
1. User can open web page, type hiccup data structures and see resulting UI

### Iteration 1..N
Goal Date:  
Description: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by yenda** [comment]
I will pledge on this idea after desktop has made some progress

**Comment by adambabik** [comment]
Would it be a similar solution to this one https://storybook.js.org? Not sure if it's viable to have designers to provide designs in code. However, I do believe we could get some help from the community by providing tools to convert designs into React Native components. 

This project can be also useful: https://github.com/necolas/react-native-web

**Comment by flexsurfer** [comment]
yes, this is exactly it @adambabik , i'm using this lib in status-electron (desktop) and want to use it here, but we will give for edit not all the code but only markup for one view, it's so simple it's not the code at all, and i believe designers could do design using it
look how simple it is
```
[view styles/transaction-sent-container
      [view styles/ok-icon-container
       [icon :icons/ok {:color components.styles/color-blue4}]]
      [text {:style      styles/transaction-sent
                   :font       (if platform/android? :medium :default)}
       "Label"]
      [view styles/gap]
      [text {:style styles/transaction-sent-description} (i18n/label :t/transaction-description)]]
     [view components.styles/flex]
```
so you need to know only Layout with Flexbox https://facebook.github.io/react-native/docs/flexbox.html
and i believe we will provide some helpers and tutorials to learn it

**Comment by flexsurfer** [comment]
https://github.com/airbnb/Lona

**Comment by flexsurfer** [comment]
02/03/18 Update
https://status-im.github.io/
1)most of react native components supported
2)status icons and colors
3)different devices
4)share fuctionality

next steps:
-all react native and status components support
-tutorials
-svg converter
-css converter

**Comment by flexsurfer** [comment]
02/04/18 Update
https://status-im.github.io/
1) help
2) svg converter
3) css converter

next steps:
-all react native and status components support

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
