### ISSUE TITLE
Create yaml front matter for all committed ideas

### ISSUE THREAD

**Issue by oskarth** [status-im/ideas#161]
Add [yaml front matter](https://jekyllrb.com/docs/frontmatter/) like e.g. https://raw.githubusercontent.com/status-im/ideas/master/ideas/121-swarm-compensation/README.md

```
---
id: 121-swarm-compensation
title: Swarm Compensation Experiments
status: in-progress
created: 2018-04-02
contributors:
    - martinklepsch
    - oskarth
---
```

to all committed ideas. This can be used to programmatically deal with ideas.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x85ffabbb19c1e5f321815fd49137f6f2be6b3c6844e3c975233a3c322a69c934](https://etherscan.io/tx/0x85ffabbb19c1e5f321815fd49137f6f2be6b3c6844e3c975233a3c322a69c934)

**Comment by oskarth** [comment]
Been done for most ideas like this https://raw.githubusercontent.com/status-im/ideas/master/ideas/58-mainnet.md - see https://raw.githubusercontent.com/status-im/ideas/master/ideas/58-mainnet.md for ideas are done. the ideas in `/ideas/` not in that list remains to be done.

@andytudhope can we bump this up to a medium? maybe do a post in Riot to ask for help on ideas repo bounties. Most are quite non technical so good if people want to contribute but aren't super familiar with Clojure/Go/RN etc.
