### ISSUE TITLE
Dynamic index for ideas

### ISSUE THREAD

**Issue by oskarth** [status-im/ideas#173]
## Problem

All dynamic information in README should be generated from idea itself. Currently this process is bad in many ways:

- It's error prone (mismatch)
- Easy to forget / ignore
- Annoying merge conflicts
- Extra time-consuming janitorial work

Use yaml front matter in idea to generate equivalent of README.

## Solution

Two approaches. One is to script updates to README, the other to create static site similar to. Since they are bounties, both can be worked on concurrently and we can see which gets done first and is most useful.

For both approaches we need:

- [ ] Yaml front matter for all ideas

### Approach 1 - script update README
- [ ] https://github.com/status-im/ideas/issues/157
- [ ] https://github.com/status-im/ideas/issues/160
- [ ] Combine above to generate README
- [ ] Later: figure out how update flow (git hook? manual run? some CI?)
- [ ] Later: classifieds

### Approach 2 - static site

Similar to eips.ethereum.org. Probably better long term.

- [x] Github pages up and running - waiting for permissions
- [x] Basic site listing - PR https://github.com/status-im/ideas/pull/185
- [x] Misc tweaks to make it feature complete with README, e.g.:
- [x] Dedup contributor index (Liquid template, treat as tags ish?)
- [x] Separate pages for ideas in different stages
- [x] Idea page theme rendering
- [x] Emojis like 🚶 
- [x] Encode missing roles (`roles-needed: - QA - PM`)?

**Comment by arnetheduck** [comment]
yaml metadata? as in, idea text and description in one file and metadata in another?

**Comment by oskarth** [comment]
I mean yaml front matter in the idea document itself. Edited.

**Comment by oskarth** [comment]
Progress on static site index. Working locally but will update PR later today. Right now we have ideas registry and commitment registry. Some tweaks needed to make it sexy etc, but basics are there. Biggest things missing now is:

- https://github.com/status-im/ideas/issues/191
- https://github.com/status-im/ideas/issues/192
- https://github.com/status-im/ideas/issues/186

once these are done I believe it is essentially feature complete with current README
