### ISSUE TITLE
Add yaml data to all ideas to reflect current README table

### ISSUE THREAD

**Issue by oskarth** [status-im/ideas#186]
See README https://github.com/status-im/ideas#idea-registry for table and see https://github.com/status-im/ideas/pull/185/files#diff-66fbd9f86c030956db51c74445a6f34c for example.

Context: https://github.com/status-im/ideas/issues/173

<blockquote><img src="https://avatars3.githubusercontent.com/u/11767950?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/ideas">status-im/ideas</a></strong></div><div>ideas - Swarm Home. New, completed and in-progress features for Status</div></blockquote>
<blockquote><img src="https://avatars2.githubusercontent.com/u/1552237?s=400&v=4" width="48" align="right"><div><img src="https://assets-cdn.github.com/favicon.ico" height="14"> GitHub</div><div><strong><a href="https://github.com/status-im/ideas/pull/185">Basic GH page table layout by oskarth · Pull Request #185 · status-im/ideas</a></strong></div><div>A start.</div></blockquote>

**Comment by oskarth** [comment]
cc @andytudhope

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x16e7ea2484be30d724256ce539f3dffe208b021b1062e167d927cd491ab54180](https://etherscan.io/tx/0x16e7ea2484be30d724256ce539f3dffe208b021b1062e167d927cd491ab54180)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x239395a40d4d3fe70baad2836d46a704fa4b9c54f49b386facf7fedfd3840f2b](https://etherscan.io/tx/0x239395a40d4d3fe70baad2836d46a704fa4b9c54f49b386facf7fedfd3840f2b)

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0x16e7ea2484be30d724256ce539f3dffe208b021b1062e167d927cd491ab54180](https://etherscan.io/tx/0x16e7ea2484be30d724256ce539f3dffe208b021b1062e167d927cd491ab54180)

**Comment by oskarth** [comment]
Eh, someone made a duplicate issue. Oops! See https://github.com/status-im/ideas/issues/161

**Comment by andytudhope** [comment]
@oskarth you need to let the team know if you close bounty issues so we can reclaim the amounts...
