### ISSUE TITLE
T-Minus 100 days to production, or, Janitors Broom Club

### ISSUE THREAD

**Issue by oskarth** [status-im/ideas#19]
## Preamble

    Idea: PROC#019
    Title: T-Minus 100 days to production, or, Janitors Broom Club
    Status: Draft
    Created: 2017-11-15
    Requires (*optional): <Idea number(s)> [TODO: Fill in with critical path swarms]

## Summary
Release the Status app to production in 100 days, enabling real live users to transact.

## Vision

We want Status to be live in production as soon as possible. This will be a quantum shift in how we think about the app, as we'll be dealing with real transactions and real users using the app regularly (hopefully). It will be both exhilarating and scary, as reality is the real litmus test for what we are all
working on. This will help guide us in all future endeavours.

In order to get there as soon as possible, we must define a critical path. A critical path is one where if you leave out something then the thing as a whole falls apart. This also means there are a lot of things that are important that we still want to be doing, but they might not be a deal breaker in terms of being live in the App and play store. The purpose of this swarm is to:

(a) outline the critical path so it is crystal clear for everyone
(b) support swarms doing the lion's share of the actual work necessary
(c) do or take responsibility for any miscellaneous janitorial work necessary to get to production in 100 days

## Swarm Participants

TBD. We want people from every department in this one, including lead swarm devs, marketing, community and general support.

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- UX (if relevant): 

## Requirements

There is one main and one auxiliary requirement for this swarm.

- Main: Have a released version of the Status app in production in 100 days, enabling real live users to transact. If the Swarm starts this week, this means end of February, 2018.

In order to fulfill the main requirement we need to figure out the scope and requirements of our production release, but this falls under Goals & Implementation plan.

- Auxiliary: It's not about telling people what to do or saying they should change their priorities. It is about showing people the critical path, to the best of our knowledge, and make it easy for people to see and work on this. This swarm is thus janitorial as opposed to managerial in purpose.

This implies any work that isn't being done by additional swarms falls under this swarms responsibility.

## Goals & Implementation Plan

Before talking about specific goals and implementation plans here, here is an outline for how I personally think about this problem. First, a universal problem: assuming you care about something, it is much easier to not launch and keep adding things than it is to remove things and launch. We must counteract this tendency fiercely.

In order for this goal to be credible, we need to be realistic about what we can do in 100 days. Exactly what do we mean by being in production? To me there are two main hallmarks for saying something is in production:

- Mainnet with transaction possibility
- Open for consumption (i.e. in App Store or equivalent)

One worry about pushing for production early with a suboptimal product (onboarding, bad perf, so-so security, confusing UX, bad Whisper scalability, etc) is that we can't push marketing and installs. This means we lose of capability of being top 10 in App store, etc. I believe this reasoning is flawed
for three reasons:

(a) It assumes too much. Scaling more than 2 orders of magnitude is not realistic (~100->10k++) without real-world experience. Additionally we'll hit up on lots of UX and misc quirks just getting an order of magnitude more users than we currently have.

(b) It relies too much on the 'big splash launch' effect and is thus fragile. We launch, things go alright but our retention is bad. Now what? It isn't iterative enough.

(c) It doesn't take into account the possibility of re-launching. We can launch a 'Status Beta' app earlier which has both the hallmarks of being in production and grow users and order of magnitude or two, doing user research etc before doing 'real' launch. If this turns out to be impossible, we can do something similar with Testflight and a much pruned list of only active users.

This would thus create two checkpoint releases. As soon as the first one is out we have real value flowing through the system, as well as real users. This will sharpen our focus even more, and provide valuable lessons for the 'big splash' launch.

Whether we count the Status Beta release as our production release or not is up to this Swarm to determine, in light of what is credible and realistic. The goal here is to not postpone an open and mainnet release several months because we don't have the guts to put Status out there.

### Minimum Viable Product

Goal Date: 2017-11-24
Description: Decision on whether to proceed with Status Beta approach or not; coarse view of critical path; insight into major things missing from current swarm's work (i.e. a 'Wishlist').

### Iteration 1..N

TBD.

Goal Date:  
Description: 

## Supporting Role Communication

Y'all.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jarradh** [comment]
we're doing a beta launch, we're keeping it in Testflight and Google play beta the launch strategy needn't be discussed in this beyond defining the deadline and max user pool, agree with Feb. The beta pools limit us to roughly max 40k installs.

This push should be entirely about solving the underlying tech problems Status has. As 'production ready' to me is, I can use Status without wanting to uninstall it. 

- It shouldn't be useless (for real transactions, mainnet)
- It can't drain my battery or make my phone hot.
too heavy on phone (performance optimisation, LES and SHH most likely culprits)
- The messaging experience is solid. (offline inboxing)
- I don't get stuck in the interface (onboarding)

We need to have a long hard look at Profiling and Optimisation. Which probably means looking at geth. 

I suspect the largest culprits are:
To anyone that understands how Whisper works it's a no brainer that in its current form it is killing the application, in both bandwidth used, proof of work and attempted decryption of all messages, as well as it's usage of DHT.

LES block header verification, look at LES2 and signed headers.

Possibly some rendering in reframe

**Comment by goranjovic** [comment]
One thing I wondered about is how do we handle bugfixing going forward. We found a number of severe regressions on a dogfooding session yesterday all across the application. E.g. group chats don't work any more, QR scanner in wallet isn't responsive, etc. 

IMO, all of these are release blockers since they prevent normal usage of even the most basic features, make a very bad first impression and are likely to cause users to uninstall the app. 

I propose that one of the janitorial tasks mentioned in this idea should be to maintain a running list of bugs whose resolution is a must-have. This would increase the visibility of such bugs and would improve the allocation priority. 

In a similar way we can maintain a nice-to-have list for lower priority bugs and select issues to put bounty on, onboard any new developers, etc - where it seems practical.

(cc @annadanchenko @asemiankevich )

**Comment by goranjovic** [comment]
I like the janitors analogy, btw. I was thinking "Ghostbusters" when I was trying to formulate the idea about a bug fixing crack squad. :ghost:

**Comment by oskarth** [comment]
Replaced by https://github.com/status-im/ideas/issues/26
