### ISSUE TITLE
Status and SOB integration

### ISSUE THREAD

**Issue by flexsurfer** [status-im/ideas#21]
## Preamble

    Idea: DEV#21
    Title: Status and SOB best friends
    Status: Draft
    Created: 2017-11-16

## Summary
Status app and SOB Dapp should be closely integrated and be a guide for programmers into new exciting crypto world

## Vision
As a programmer who is new in crypto world, i want to start work on SOB open bounties and Status should help me to do that easily.
1) Suggest to install Status on SOB page
2) SOB should be in onboarding options in Status
3) After creating new account SOB Dapp should be opened and SOB should suggest to add this account (address) as default
4) SOB chatbot to share open bounties with friends or in groups

As a potential investor i want to find and fund interesting for me GitHub issues
1) Suggest to install Status in SOB comment on GitHub 
2) SOB for investors should be in onboarding options in Status
3) GitHub page should be opened within SOB chatbot
4) It should be possible to fund and sentTransaction to SOB contract

## Swarm Participant

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: @andytudhope
- Contributor: 
- UX (if relevant): 

TBD
## Requirements

TBD
### Minimum Viable Product

Goal Date:  
Description: 
TBD
### Iteration 1..N
Goal Date:  
Description: 
TBD
## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jarradh** [comment]
Awesome! Could you please clarify the Onboarding options? I didn't quite follow.

In this I imagine that bounties should be visually represented, overlaid over the application GUI as markers/pins for anything that is a SOB bounty. Displaying the bounty title, balance, and with a link to the github issue.

Users show be able to:
- create issues that are visually represented in application if they submit a bounty for it
- open issues 
- add to bounty for the issue directly in the application

**Comment by flexsurfer** [comment]
![image](https://user-images.githubusercontent.com/11790366/33060301-d9a03130-cea8-11e7-997f-98afc8c194e9.png)

**Comment by andytudhope** [comment]
Happy to help here @flexsurfer - can prob give you at least 5h/week if you need it.

**Comment by naghdy** [comment]
Thanks for driving this Andrey. I'm wondering if practically, developers and orgs are going to want to use SOB on their mobile device through the Status app? Isn't it something that would be more commonly done on mobile?

On mobile, I can see some valid use cases for:

1.  Creating a bounty on bugs found within the app, then optionally allocating some funds to fix it.
2. Browsing open bounties, and optionally adding some additional funds to them.

Both use cases seem interesting. From a priority perspective [1] > [2]. I personally wouldn't put this on the critical path for either MVP or a new and improved SOB.

**Comment by naghdy** [comment]
Closing this as its gone stale. Feel free to re-open if its still relevant or if there is someone working on it.
