### ISSUE TITLE
Ensure ideas are sorted properly

### ISSUE THREAD

**Issue by oskarth** [status-im/ideas#212]
## Problem

Ideas aren't sorted making it hard / annoying to find recent ideas.

## Solution

Ensure ideas are sorted numerically in https://ideas.status.im/all and https://ideas.status.im/people

Requires Jekyll Liquid template filtering by `sort_by`. Ran into some issues where `bundle exec jekyll serve` intermittently wouldn't run. Seems like it had something to do with ids showing up as null in some template, so might need to do some checking there.

Related: https://github.com/status-im/ideas/issues/158

## Acceptance criteria

Ideas are sorted numerically and `bundle exec jekyll serve` / GH page always renders.

<blockquote><div>Status - Ideas</div><div><strong><a href="http://ideas.status.im/all">Ideas</a></strong></div><div>Swarm Home. New, completed and in-progress features for Status.</div></blockquote>
<blockquote><div>Status - Ideas</div><div><strong><a href="http://ideas.status.im/people">People</a></strong></div><div>Swarm Home. New, completed and in-progress features for Status.</div></blockquote>

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xf43077819c7fa546ec6a3be78e13201237ec4ba1ed9142cfc4501fb7f01b5825](https://etherscan.io/tx/0xf43077819c7fa546ec6a3be78e13201237ec4ba1ed9142cfc4501fb7f01b5825)

**Comment by debragail** [comment]
supposedly sort is returning null on just the local.  have you tried testing it not locally?  I researched the problem and that seemed to fix it for most.

**Comment by debragail** [comment]
removed
{%- seo -%}
ideas/vendor/bundle/ruby/2.5.0/gems/minima-2.5.0/_includes/head.html



from Debras-MacBook-Pro:ideas 0PHE1IA$ bundle exec jekyll serve --safe
Configuration file: /Users/0PHE1IA/status/ideas/_config.yml
            Source: /Users/0PHE1IA/status/ideas
       Destination: /Users/0PHE1IA/status/ideas/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
  Liquid Exception: Liquid syntax error (/Users/0PHE1IA/status/ideas/vendor/bundle/ruby/2.5.0/gems/minima-2.5.0/_includes/head.html line 5): Unknown tag 'seo' included in /_layouts/default.html
jekyll 3.7.3 | Error:  Liquid syntax error (/Users/0PHE1IA/status/ideas/vendor/bundle/ruby/2.5.0/gems/minima-2.5.0/_includes/head.html line 5): Unknown tag 'seo' included

**Comment by debragail** [comment]
<img width="1172" alt="screen shot 2018-05-01 at 17 36 14" src="https://user-images.githubusercontent.com/552529/39499981-38b043a4-4d66-11e8-8b81-54d3498706af.png">

**Comment by debragail** [comment]
http://shopify.github.io/liquid/basics/types/#nil

**Comment by debragail** [comment]
This is already fixed it seems.

**Comment by debragail** [comment]
This is fixed and should be closed.

**Comment by oskarth** [comment]
@debragail you are right, thanks! Seems like the "Fixes" keyword didn't work in https://github.com/status-im/ideas/pull/230

cc @andytudhope for bounty payout before closing this

**Comment by andytudhope** [comment]
Was handled some time ago :wink: https://etherscan.io/tx/0x41122bed3e0ba844d2a1ef57086e3b2d510036d71d9ca1815586b54f3c586198

**Comment by alexkohler** [comment]
Hey @oskarth & @andytudhope, I don't think I ever received the payout for this issue? Did this go to the correct address? :smile:

**Comment by andytudhope** [comment]
Hey @alexkohler - sorry, I was referencing the wrong manual payout 😅 

The reason this was not picked up is that you fixed 2 issues in one PR, which we currently have a fix outstanding for. So, I have paid you manually for this while we work on that.

https://etherscan.io/tx/0x9fa2dfb7c17345f348e8efea4bcf21f508d08844ecd58373420f46019ca10a75

Sorry for the inconvenience!
