### ISSUE TITLE
Add lead contributor to idea registry

### ISSUE THREAD

**Issue by oskarth** [status-im/ideas#214]
1. Add a column lead contributor to https://ideas.status.im/all
2. Fill in missing data for ideas listed at https://ideas.status.im/all

<blockquote><div>Status - Ideas</div><div><strong><a href="http://ideas.status.im/all">Ideas</a></strong></div><div>Swarm Home. New, completed and in-progress features for Status.</div></blockquote>
<blockquote><div>Status - Ideas</div><div><strong><a href="http://ideas.status.im/all">Ideas</a></strong></div><div>Swarm Home. New, completed and in-progress features for Status.</div></blockquote>

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xda9267ea1deefbc4c93f9626f2d2ba720d8d217260ea599e3e49579e0217e232](https://etherscan.io/tx/0xda9267ea1deefbc4c93f9626f2d2ba720d8d217260ea599e3e49579e0217e232)

**Comment by debragail** [comment]
Why are you spending the time building this when you can use Jira or Github issues?

**Comment by oskarth** [comment]
(Replied here: https://github.com/status-im/ideas/pull/221#issuecomment-384976455)

**Comment by debragail** [comment]
Finished the 2nd half of the issue.  Please see PR @oskarth.

**Comment by debragail** [comment]
@oskarth I'm sorry.  I still don't know what the missing data is.  I'd be happy to fix it but I'm not sure what is missing since the .md files that don't have a lead-contributor don't have one anywhere in the file they have contributor though.

**Comment by oskarth** [comment]
All the ones here https://ideas.status.im/all that don't have a 'Lead Contributor'. Fixed most in other PR, but seems like there are a few left. Info should be inside the markdown as text (lead contributor).

**Comment by debragail** [comment]
@oskarth ah I understand now
