### ISSUE TITLE
Ideas UI not formatted for mobile browser 

### ISSUE THREAD

**Issue by debragail** [status-im/ideas#226]
in Safari on iOS the menu bar doesn’t size and the table doesn’t format for mobile.

This needs to be designed for mobile and made responsive.

**Comment by oskarth** [comment]
Thanks for the report! Solutions is probably to figure out a better way to do responsive layouts (not tables) - maybe collapse some columns when on phone or whatnot. Requesting bounty for this.

**Comment by debragail** [comment]
I still don’t know why you’re building a product management tool from scratch

**Comment by andytudhope** [comment]
I would suggest that it is because we have enough unique requirements - and future plans of what swarms will be/do/look like - that it is worth it for us to put in the effort required to build something bespoke for us. Maybe Oskar has further thoughts, but either way, thanks for the report.

**Comment by status-open-bounty** [comment]
![Contract deploying](https://openbounty.status.im/img/deploying_contract.png)
Transaction: [0xd195e65724ac9956a413b838e5cc1ea14650017839b0b57de6de64a0178ef06c](https://etherscan.io/tx/0xd195e65724ac9956a413b838e5cc1ea14650017839b0b57de6de64a0178ef06c)
