### ISSUE TITLE
ENS subdomain username registrar 

### ISSUE THREAD

**Issue by 3esmit** [status-im/ideas#27]
## Preamble

    Idea: <to be assigned>
    Title: ENS subdomain username registrar 
    Status: Draft
    Created: 2017-11-20

## Summary
Provide a Registrar for Status users to share their identity easier with their friends. 

## Vision
Sometimes scanning a QRCode in your friend smart phone is not the best, perhaps it would be easier to provide them a URL through ENS. Status would register their domain and upon a fee in SNT register their Identity address to an available subdomain. 

Allow the change of address might not needed, as them would be registered against an Identity Contract, that internally can change the manager key.

## Swarm Participants

- Lead Contributor: @3esmit

### Minimum Viable Product

Goal Date:  
Description: Users can register (FIFS) an available username in Status's ENS subdomain
 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by 3esmit** [comment]
Suggested ENS registry names (that are already owned by Status):
```
seekyou.eth
ethuser.eth
namereg.eth
isoname.eth
findmeat.eth
rarename.eth
uniuser.eth
0number.eth
allonym.eth
anonymd.eth
anonyms.eth
bynamed.eth
neoname.eth
newname.eth
regname.eth
reguser.eth
uniname.eth
uniqueid.eth
myetheruser.eth
usereth.eth
usernet.eth
userreg.eth
netuser.eth
moniked.eth
mynamed.eth
```

**Comment by naghdy** [comment]
Any update to this swarm @3esmit ?

**Comment by richard-ramos** [comment]
We could consider supporting RSA in future upgrades. I've researched the current state of RSA in Ethereum and I found https://github.com/ethereum/EIPs/issues/74 but it seems to be stuck on limbo, however, there's a repository that contains a contract to verify RSA signatures: https://github.com/adriamb/SolRsaVerify

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
