### ISSUE TITLE
ERC20 token support

### ISSUE THREAD

**Issue by jeluard** [status-im/ideas#3]
Idea code: DEV#003
Status: Done
Created: 2017-11-08

## Summary

Add ERC20 support

## Idea proposal

As a user I want my [ERC20](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-20-token-standard.md) tokens to be first class citizen.

## Swarm Participants

* Lead Contributor: @jeluard
* Contributor: @goranjovic
* Support: @3esmit
* Tester: @asemiankevich

Swarm channel: **3-erc20**

## Requirements

A user should be able to manage its ERC20 tokens pretty much the same way as ETH.
In particular `wallet` and `send` command must support ERC20 tokens.

As a first step considered ERC20 tokens will be based on a static list embedded in the application. This might be revisited later (see #18).

ERC20 extensions might also be considered: [ERC223](https://github.com/ethereum/EIPs/issues/223), [Minime](https://github.com/Giveth/minime) ([SNT](https://etherscan.io/token/StatusNetwork) itself is a Minime token).

## Zeplin references

* Assets https://zpl.io/blwD8ka
* wallet main screen (with list of assets shown + managin assets) https://zpl.io/b6d1eNV

## Board
https://github.com/status-im/status-react/projects/4

## Goals & Implementation Plan

Following features should be considered:

* list wallet tokens
* provide default token
* send tokens to a contact
* request token from a contact
* get current price
* get historical price
* get token details (historical price, market cap, # tokens, volume, crowdsale)
* list historical transactions
* add gas and data support when sending transaction
* chart graphs

Can be split in 4 categories:

* wallet token details (access and management)
* token details (static and dynamic data)
* token price details
* token transactions

Token details will require some metadata currently not available in ethereum.
Token price details can be provided by `cryptocompare`.

### Minimum Viable Product

List user tokens and display token details

Goal Date: 2017-12-01
Description: token list and details

### Iteration 1

Allow sending and requesting tokens.

Goal Date: 2017-12-15
Description: send/request tokens

### Iteration 1 acceptance criteria (functionality to demo at the end of iteration):

- [x] User is able to `send` STT (status test token) under Ropsten testnet in `Wallet`
- [x] User is able to `request` STT (status test token) under Ropsten testnet in `Wallet`
- [x] Wallet is updated accordingly send/request transactions performed: main wallet value is updated, asset value is updated (both wallet main screen and asset details screen)

Demo acceptance:

- [x] functionality above is tested prior the demo
- [x] functionality above is merged in develop after it is tested and prior the demo so we avoid to demonstrate something we do not have in develop build

### Iteration 2

Show token historical data and update percentage info

Goal Date: 2017-12-22
Description: token historical data

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jeluard** [comment]
I pledge focus 20h/w.

**Comment by asemiankevich** [comment]
I pledge focus 15h/w.

**Comment by goranjovic** [comment]
I pledge focus 20 h/w

**Comment by goranjovic** [comment]
Until we start with #8 I can pledge full focus on this - 40 h/w

**Comment by goranjovic** [comment]
Relevant pre-existing issues:

https://github.com/status-im/status-react/issues/1951
https://github.com/status-im/status-react/issues/1745
https://github.com/status-im/status-react/issues/1722
https://github.com/status-im/status-react/issues/1654
https://github.com/status-im/status-react/issues/1528
https://github.com/status-im/status-react/issues/1653

**Comment by sla-shi** [comment]
I'd like to contribute to this idea up to ~10hrs a week

**Comment by jeluard** [comment]
@sla-shi I'd like to add you as Evaluator. Also we will need some nice wiki doc. WDYT?

**Comment by asemiankevich** [comment]
Action items after today's cacth-up:

- [ ] @goranjovic to create list of issues

- [ ] @jeluard and @goranjovic after the list of issues is created - define the doable scope for `Iteration 1`  (12/1)  and for future ones. Maybe we can make those iterations for 2 weeks to have more easier tasks?

- [ ] bring some clarify regarding the tokens request functionality @andmironov , @denis-sharypin can you assist with that?

- [ ] add references to the zeplin mocks

**Comment by jeluard** [comment]
MVP has been successfully implemented. Browse the [report](https://github.com/orgs/status-im/teams/status/discussions/4) for more details.

**Comment by jeluard** [comment]
First iteration has been successfully implemented. Browse the [report](https://github.com/orgs/status-im/teams/status/discussions/10) for more details.

**Comment by jeluard** [comment]
### Post Mortem

##### What could be improved

[App structure refinement](#61) was defined during the first iteration and significantly impacted the scope of this iteration. Specifically @goranjovic work around asset details had to be removed.

A number of technical elements has been discovered and added to the todo list during development. It appears primordial to spend some time during the first days to have a detailed understanding of what's to be done and technical impacts. It appears our decentralized nature makes some usually simple things harder to implement.

Finally we discovered pretty late some technical limitations that prevented us to implement some features (e.g. token transaction history).

#### What went well

Overall implementation went smoothly and we had fast test cycle thanks to @asemiankevich .
