### ISSUE TITLE
General architecture & patterns for status react

### ISSUE THREAD

**Issue by janherich** [status-im/ideas#31]
## Preamble

    Idea: <to be assigned>
    Title: General architecture & patterns for status react
    Status: Draft
    Created: 2017/11/22

## Summary
Define and adhere to architecture vision for status react. Have all the best practises clearly defined in one place.

## Vision
Our architecture (shape and organisation of data + code) is not optimal, what's worse it's nowhere clearly defined and discussed about. The purpose of this Idea is to improve it by identifying all the problematic parts of our current architecture, capture them as user stories, fix them and properly document it for future reference.

## Swarm Participants

- Lead Contributor: @janherich
- Testing & Evaluation: 

## Requirements

1. Re-frame database shape is reflecting the the app access patterns (writing for handlers, reading for subscriptions) by correctly indexing for fast lookups and normalised storage for fast, consistent updates
2. Subscriptions form efficient signal graph, with minimal amount of Level-1 subscriptions and highest possible re-use of all subscriptions
3. All the events in application are related to outside inputs and there are no artificial intermediate events anymore
4. Co-effects and effects are isolating the side-effects *everywhere* and we re-use them to highest possible degree

### Minimum Viable Product

Goal Date: 2017-12-08 
Description:
- [ ] Database is refactored according to point 1

### Iteration 1..N
Goal Date: 2017-12-08 
Description: Requirement 1 should be done

Goal Date: 2017-12-24 
Description: Requirement 2 should be done

Goal Date: 2018-01-14 
Description: Requirement 3 should be done

Goal Date: 2018-02-07 
Description: Requirement 4 should be done

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by janherich** [comment]
# User Stories

## 1. Re-frame database shape is reflecting the the app access patterns (writing for handlers, reading for subscriptions) by correctly indexing for fast lookups and normalised storage for fast, consistent updates

When designing the data-structure of re-frame app-db, always have in mind how the data will be accessed and how it will impact performance and consistency.
For example whenever you need random access to any piece of data which will be red much more often then wrote, put it in map and construct the key in such way that simple and fast lookup (without additional filtering) is guaranteed, even if it means that construction of key is little bit more complicated/slower. 
If something has to be unique, put it in set.
Any derived data shouldn't be in database at all and should be computed from source data on fly by default (in super rare cases, we can revisit that when it would hurt performance).

### Current situation

Some derived data are stored in db and recalculated explicitly (tags for discovery statuses). But the most problematic thing is proliferation of data indexed by message-id (`:message-data`, `:message-id->transaction-id`, `:message-status`, `:unviewed-messages`, `:handler-data`), which all are just workarounds around the fact that the primary path where messages live (`:messages`) is not indexed in any way.

**Comment by yenda** [comment]
I can pledge some of my time that I spend in idea 9 since the two seems closely related

**Comment by naghdy** [comment]
Closing this as it hasn't been touched in ~3 months. Feel free to re-open if this is something that we are going to tackle soon
