### ISSUE TITLE
Rename sections

### ISSUE THREAD

**Issue by andmironov** [status-im/ideas#32]
## Preamble

    Idea: Rename sections in bottom navigation of the App
    Title: Rename navigation sections
    Status: Draft
    Created: 2017-11-22

## Summary
Basically the idea is to change the order of the sections and rename "Chats" to "Tabs" and "Contacts" to "Favourites" to indicate a more generic purpose of those screens. 

The idea of changing the order and putting "Tabs" and "Contacts" in the middle seems relevant as these screens are both related to chat, yet "Wallet" and "Discover" are different and it makes sense to put them at the first and last positions respectively.

The words "Tabs" and "Contacts" have been chosen on the basis of being commonly used in browsers which fits well in Status since it's a browser as well.

<img width="428" alt="screen shot 2017-11-22 at 15 35 44" src="https://user-images.githubusercontent.com/3115606/33127738-db17de6c-cf9a-11e7-9e7b-e21ca8bb18ae.png">

All resources available for export here zpl://screen?sid=5a1575cef4f55be22789c352&pid=5863cdcee68455850f1929f2

## Swarm Participants

- Contributor: 
- UX: @andmironov

## Goals & Implementation Plan
The goal is to decrease confusion for users by using more generic and at the same time representative section names.

After completing this, we can move on to implementing the Omnibar and Chat redesign.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by naghdy** [comment]
I'm curious to understand why we should rename "Chat" to "Tabs"?

**Comment by chadyj** [comment]
We can close this as tabs are being address in #61.
