### ISSUE TITLE
Remove swipe-through navigation and introduce a tab-based screen hierarchy instead 

### ISSUE THREAD

**Issue by andmironov** [status-im/ideas#33]
## Preamble

    Title: Remove swipe-through navigation and introduce a tab-based screen hierarchy instead 
    Status: Draft
    Created: 2017-11-22

## Summary
Remove swipe-through navigation and introduce a tab-based screen hierarchy instead.

## Vision
Tab-based screen hierarchy will make it possible to use swipes inside the screens:
- Swipe a chat row to quickly access actions such as "delete chat"
- Swipe a token row to access actions such as "delete" and "hide"

![w2](https://user-images.githubusercontent.com/3115606/33166820-b56e31ae-d04c-11e7-8525-9e8393c645f9.png)

## Swarm Participants

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: 
- UX: @andmironov

## Requirements

- Prepare more use cases that will be possible after implementation of this feature. I guess it would be useful  in Discover screen.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by buhrmi** [comment]
Hello, just found this linked in the status riot chat. Is the intention that people will be able to simply enter any URL in the bar? If no, I think they should be able to. It would be nice if people can add dapps simply by typing in the URL and add a bookmark, like normal webbrowsers...

**Comment by andmironov** [comment]
@buhrmi hi, thanks! yes, that was exactly the idea, since Status is a browser, we did not want to create any obstacles to access a DApp directly by entering a URL in the address bar. This is why we decided to add this what we call it "the omnibar" which is basically a search bar and an address bar at the same time.

**Comment by buhrmi** [comment]
that's awesome. I think many people will love it. It should be the default screen right after launching status. People will instantly feel familiar, and the account setup can be done via a more traditional wizard rather than a/the "console". Console can be moved into the background as a hidden feature.

**Comment by buhrmi** [comment]
is there a way to fund the development of this new omnibar-centric layout? I'd like to throw an ether or two at that...

**Comment by chadyj** [comment]
Can be addressed in #61 @jeluard?

**Comment by jeluard** [comment]
@chadyj Completely! That would make sense as this one is probably not broad enough to be a standalone swarm.
