### ISSUE TITLE
Github Bot

### ISSUE THREAD

**Issue by yenda** [status-im/ideas#37]
## Preamble

    Idea: 37-github-bot
    Title: Github Bot
    Status: Draft
    Created: 2017-11-22

## Summary

Build a Github bot to automate various tasks and processes on our Github repositories

## Vision

Github bots are used on repositories such as react-native to automate some tasks that would be too repetetive or cumbersome for a human to do.

As a community manager I want to be able to garantee that external contributors PRs don't get forgotten and get treated within a reasonnable timeframe by the team
As a tester I want to be warned when I have to test migrations in a PR

The bot could mostly be developed via the bounty system in order not to distract the team too much from the critical path of development.

;;;;; template
## Swarm Participants

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- UX (if relevant): 

### Minimum Viable Product

Goal Date:  
Description: 

### Iteration 1..N
Goal Date:  
Description: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jeluard** [comment]
If we chose to use GH `projects` we could automate part of the workflow too: move to `ready for testing` after 2 members approval, move to `tested` when the `tested` label is added, ..

**Comment by oskarth** [comment]
Great idea. What do you think is a good MVP user story that we can bounty up?

**Comment by jeluard** [comment]
[Probot](https://probot.github.io/) seems relevant to this idea.

**Comment by jeluard** [comment]
Also see an example of a bot manipulating labels: [wafflebot](https://help.waffle.io/wafflebot-basics/getting-started-with-the-wafflebot/how-to-use-wafflebot)

**Comment by PombeirP** [comment]
Implemented with probot and added `#status-probot` room to Slack to collect notifications from the bot.
