### ISSUE TITLE
Developers! Developers! Developers!

### ISSUE THREAD

**Issue by jeluard** [status-im/ideas#4]
Idea code: DEV#004
Title: Developers! Developers! Developers!
Status: WIP
Created: 2017-11-09

## Summary

Towards a better environment for developers

## Vision

Status provides an ethereum based platform for developers. It must be comprehensive, accessible and complete as much as can be.
This is specifically targeting developer experience.

## Swarm Participants

* Lead Contributors: @jeluard
* Contributor: @pablanopete 
* Contributor: @andytudhope
* Designer: ?

### My first bot

Bot rely on easy to grasp technologies. My first bot should be testable in 5 minutes.

### Bot API

Bots provide great power and allow developers to tightly integrate in status.
API must cover all cases and have meaningfull semantic. There should be no hole in the paint.
Documentation should detail all available features. 

Higher level APIs for common scenario might be considered too (converstations, ..).

It makes sense to test integration with existing ethereum technology to get some hands-on experience (livepeer, trustlines, raiden, [favor network](https://github.com/status-im/hackathon/issues/140)).

### DApp integration

DApps can be browsed natively in status using `web3` object. It makes sense to offer some integration with others status features:

* bot manipulation
* contacts access
* ..

Special care will have to be payed to the security.

### Integrated dev environment

`status-desktop` offers great potential for an integrated dev environment.

* device discovery and one-click bot deployment
* inline `suggestions` preview
* bot / DApp debugging
* inline bounty integration

### Seamless deployment experience

Once a bot is developed and tested it must be made available to others. This should be done as much as possible in a decentralized way (swarm).
Identity and versioning might also be considered here.

## Goals & Implementation Plan

Scope is very broad and some of the listed scenarios depend on non existing tools (e.g. `status-desktop`).

We want to use this umbrella idea to detail mid-term goals and keep them in mind to implement some of the more concrete ones.

Specifically following will be implemented:

* improved bot API documentation (first bot and complete API)
* identify missing APIs and make it sound (both bot and DApp integration)
* detailed plan for `status-desktop` dev env
* detailed plan for deployment experience

### Minimum Viable Product

Updated documentation, bot and DApp API.

Goal Date: _To be defined_
Description: a sound set of dev APIs

### Iteration 1

Define concrete steps for `status-desktop` role and deployment process.

Goal Date: _To be defined_
Description: a clear plan for the future

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jeluard** [comment]
I pledge focus 40h/w.

**Comment by andytudhope** [comment]
I can pledge 5hr/week to this as a contributor who wants to influence the direction this swarm takes based on the feedback I have gathered from early adopters already. My first comment is that we need to get the Watchman dependency out for Windows users of `status-dev-cli` as that is a total blocker for a lot of Windows devs.
We had some efforts underway after the hackathon to improve the debugging features around the API, perhaps that is a first iterative step toward a better overall developer experience we can get going on before the tools mentioned that don't exist yet are developed.

**Comment by naghdy** [comment]
Considering this swarm is for building out our developer eco-system, it is definitely important. However it hasn't been touched in many months. 

We should spin up a Swarm after Beta that focuses on:
- Speccing a clear SDK (including a potential refactor on the Go side)
- Improving developer documentation
- Design best practices for DApp developers

For now, I'm going to mark this as closed and change the Swarm name in Slack to simply a #channel focused on developers
