### ISSUE TITLE
Implement native screen animations and swipe-back gesture on iOS + bug fixes

### ISSUE THREAD

**Issue by andmironov** [status-im/ideas#41]
## Preamble

    Title: Implement Screen Animations and swipe-back gesture on iOS
    Status: Draft
    Created: 2017-11-23

## Summary
Implement native screen animations (slide left when opening a screen, slide right when go back, slide up when opening a fullscreen popup, slide down when closing a popup). And implement swipe-back gesture on iOS.

Also, let's remove the "accidental tap" when you are trying to scroll/swipe a list on IOS.

Here's an example of a native "slide in/slide out" animation on IOS https://framer.cloud/HuwfG

## Vision
Native screen animations create a more smooth and native experience and provide a visual sense of screen hierarchy 

## Swarm Participants

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: 
- UX: @andmironov

### Minimum Viable Product

Goal Date:  
Description: 

### Iteration 1..N
Goal Date:  
Description: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jeluard** [comment]
I am interested in working on this as I believe it will improve perceived UI performance. It's also an opportunity to simplify our internal screens navigation model and implement deep linking.

@andmironov Can you clarify what you expect in the MVP?

**Comment by naghdy** [comment]
Similarly here. Hopefully this was done as part of #61 otherwise we can open as a bug.
