### ISSUE TITLE
Multi wallet support

### ISSUE THREAD

**Issue by jeluard** [status-im/ideas#42]
Idea code: DEV#042
Title: Multi wallet support
Status: Draft
Created: 2017-11-23

## Summary

Multiple wallet management

## Vision

Status provides a comprehensive wallet allowing to manage your main Status ethereum address.
As a user I want to leverage this wallet to manage other addresses.

We will also consider if switching address should also impact other status features (DApps browsing, bot usages, ..)

## Swarm Participants

* Lead Contributors: ?
* Contributor: ?
* Contributor: ?
* Evaluator: @jeluard
* Evaluator /  Tester : @asemiankevich 

### Wallet switching address

New addresses can be added and browsed in the wallet. All existing features (browsing funds, access to historical data, send/request funds) are functioning.

### Abstraction for external wallet access

Status must be able to interract with `hardwallet` and other hardware wallet. Consider how this impact our current wallet abstractions.

### Minimum Viable Product

A new address can be added and switched to. All wallet features are functioning.

Goal Date: _To be defined_
Description: any ethereum address can be used in wallet

### Iteration 1

Decide how switching address impacts other Status features

Goal Date: _To be defined_
Description: decision on how address switching impacts Status 

### Iteration 2

Identify specific changes needed to interact with `hardwallet`

Goal Date: _To be defined_
Description: `hardwallet` can be used in Status wallet

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by asemiankevich** [comment]
add me as a tester here

**Comment by jeluard** [comment]
It has to be clarified the following points:
* do we want to have new wallets browsable only in `wallet` tab (not affecting others features e.g. whisper identity, command and web3 integration)
* how are accounts tied to wallets

**Comment by grishick** [comment]
Would be happy to test this feature. As a DApp developer, I would like to be able to use my wallets created in other HD-enabled wallet AppStore Toshi and Mist with all of the Status features, and especially with DApps inside Status

**Comment by grishick** [comment]
Damn autocorrect :) I meant “other HD-enabled wallet apps like Toshi and Mist”.

**Comment by jeluard** [comment]
@grishick We are not working on this yet but I will keep you posted when we will!

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
