### ISSUE TITLE
Messages Update

### ISSUE THREAD

**Issue by andmironov** [status-im/ideas#43]
## Preamble

    Idea: Update and clean up the messages in Chat. Add missing message types.
    Title: Messages Update
    Status: Draft
    Created: 2017-11-24

## Summary
There is a lot of UI/UX issues with the chat at the moment. Here i've put together all issues with messages and message types.

- Added text buttons and buttons with options. Use case: respond to a transaction request: Send/Decline;
- Align User Picture to the bottom of the message bubble. This is to make it easier to see from who is the message if it's too long and exceeds the visible screen height;
- Add/update message types: Location, Transaction, Link, Image;
- Message groups. If a group of messages has been sent one after another with a short time gap between, group them together (put them closer, do not show the avatar and the name next to each message);
- Added "Scroll to latest messages" button;
- Added "Only visible to you" message type. To be discussed. As a use case i suggest showing some service notification as a message from a Status Bot. This is a rather wide topic. Needs more thought to be put in and a set of rules on when do we show those messages. One more use case: when a person uses a command to send a request to a bot inside of a chat with somebody else. They get a response from that bot inside the same chat but "Only visible to you" message;
- Took the name out of the message. Let's try following this rule: "What's inside the message bubble is the messages content. Put all meta information outside the bubble";
- To save some screen real estate we could get rid of names and avatars in the 1-1 chat, but as you can see for now there is no distinction between a group chat and a 1-1 chat. This is because it would be possible that for instance a bot can send a message inside a 1-1 chat;
- Cleaned up some mess: made padding smaller and consistent, mede font-size for names/message meta info smaller;
- To be added later: voice messages, messages with a set of images, message with a file attachment and more.

![messages](https://user-images.githubusercontent.com/3115606/33204583-175e509c-d115-11e7-9be1-cd99303d1b69.png)

## Vision

![screens_messages2](https://user-images.githubusercontent.com/3115606/33204789-b2b99614-d115-11e7-82f4-79f3a3af8241.png)

## Swarm Participants

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- UX: @andmironov

### Minimum Viable Product

Goal Date:  
Description: 

### Iteration 1..N
Goal Date:  
Description: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by naghdy** [comment]
@andmironov or @chadyj  - was this fixed in #61 ? If not, then we can add it there as a bug rather than as a swarm
