### ISSUE TITLE
Message viewers for Chat

### ISSUE THREAD

**Issue by andmironov** [status-im/ideas#44]
## Preamble

    Idea: <to be assigned>
    Title: Message viewers for Chat
    Status: Draft
    Created: 24-11-2017

## Summary
At the moment there are missing these message viewers for the chat:
- Image
- Location
- Transaction

## Vision
These are the initial states, need to add more states, will do soon, work in progress. 
Re-using the transaction details screen from wallet for consistency.

![screens_viewers2](https://user-images.githubusercontent.com/3115606/33205332-9bb5119e-d117-11e7-9d08-6713295138c0.png)

## Swarm Participants

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- UX:  @andmironov

### Minimum Viable Product

Goal Date:  
Description: 

### Iteration 1..N
Goal Date:  
Description: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jarradh** [comment]
Transaction and Location ones are do-able, 
Location one should be designed/implemented in a way that they can do so with our api

**Comment by naghdy** [comment]
Marking these as closed because they haven't been tackled. We can re-open them as bugs if they weren't completed as part of #61
