### ISSUE TITLE
Update the text input

### ISSUE THREAD

**Issue by andmironov** [status-im/ideas#45]
## Preamble

    Title: Update the text input
    Status: Draft
    Created: 27-11-2017

## Summary
Clean up the text input, put all actions and commands in one row to make it more flexible. Re-arrange the actions and commands;

![input](https://user-images.githubusercontent.com/3115606/33206203-7cfe8138-d11a-11e7-8e1e-56d6ea705d6b.png)

## Vision
To make it more clear for people how the text input and commands work, decided to re-arrange the text input. Main points:
- New Text Input Look
Update text input, put the actions and recent commands in the same scrollable row;
- Show command descriptions on long tap;
- Make it easy to cancel a command by adding an `x` icon next to it;
- Update Send Button States
Disable the send button when there is nothing to send. Point the Send Button Up if it's a text message or something that is ready to be sent to the chat directly. Point the Send button right, if there are some extra steps required;
- Show the recent commands first, make the list horizontally scrollable;
- Remove custom emoji (use native emoji instead);
- Add image chooser, for now let's make it simple and add a way to add only one image at a time. Adding multiple images requires more work to be done;
- Added a custom keyboard with a set of pre-defined options;
- Hide Keyboard on swipe down;
- For now it remains unclear how the voice messages work, we can just remove the mic icon for now.

This is work in progress, open for any discussion and suggestions

![screens_inputs](https://user-images.githubusercontent.com/3115606/33206218-8b694ce4-d11a-11e7-8535-7993bf5e7efe.png)

## Swarm Participants

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- UX: @andmironov

### Minimum Viable Product

Goal Date:  
Description: 

### Iteration 1..N
Goal Date:  
Description: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by naghdy** [comment]
To be honest, I'm a bit confused about the /<text> things do in the input text.

**Comment by qnou** [comment]
@andmironov if you are removing custom emojis. What does the new smiley face icon represent?

**Comment by feuGeneA** [comment]
[The card for this Issue](https://github.com/status-im/ideas/projects/5#card-5856563) is currently in [the "To Do" column](https://github.com/status-im/ideas/projects/5#column-1800074) in [the "Status - Core App" Project board.](https://github.com/status-im/ideas/projects/5)  Shall we move it to the Done column?
