### ISSUE TITLE
Browser update + new chat header look

### ISSUE THREAD

**Issue by andmironov** [status-im/ideas#46]
## Preamble

    Idea: <to be assigned>
    Title: Browser update + new chat header look
    Status: Draft
    Created: 24-11-2017

## Summary
The idea to treat Dapp's webview and Chat with a person as first class entities requires some UI updates. Need to add a regular browser as well to be able to open in-chat links.

![top](https://user-images.githubusercontent.com/3115606/33206677-0f28ceb4-d11c-11e7-8690-e2d83ab08bd1.png)

## Vision
Made the Chat header and Browser header look similar. See browser window in action https://framer.cloud/HuwfG

![screens_browser](https://user-images.githubusercontent.com/3115606/33206751-597f5104-d11c-11e7-87de-5b44817b0696.png)

## Swarm Participants

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- UX: @andmironov

### Minimum Viable Product

Goal Date:  
Description: 

### Iteration 1..N
Goal Date:  
Description: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jarradh** [comment]
Agreed this is desired and needs to happen

**Comment by naghdy** [comment]
Closing this as its not so much a swarm, but rather a UI fix. If this hasn't happened as part of #61 then we should do that.
