### ISSUE TITLE
Fix them all

### ISSUE THREAD

**Issue by annadanchenko** [status-im/ideas#50]
## Preamble

    Idea: DEV#50
    Title: Fix them all
    Status: Draft
    Created: 2017-11-28

## Summary

There are bugs that sneak from time to time and just must be fixed. Unfortunately, they are not part of any idea but ruin user experience with the Status app. We need to dedicate some time per week to fix and verify such bugs. 

For example: https://github.com/status-im/status-react/issues/2426

Any team member can mark any bug for the cleanup, e.g with `fix them all` label. Mind the bugs that we can delegate to the community as bounty issues, they will get label `bounty-awaiting-approval`! 
## Vision

- We dedicate x amount of time weekly to keep the house clean (fix/verify bugs)
- We mark bug with `fix them all` label whenever we think it's not acceptable for the app to behave like this. 

## Swarm Participants

- Lead Contributor: 
- Testing & Evaluation: @annadanchenko 
- Contributor: @annadanchenko 5 hours/week
- Contributor: 
- UX (if relevant): 

### Minimum Viable Product

Goal Date: 2017-12-01
Description: Fix at least 2 bugs from list below
https://github.com/status-im/status-react/issues/2426
https://github.com/status-im/status-react/issues/2314

Filter to see current open issues with label `fix them all` https://github.com/status-im/status-react/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+label%3A%22fix+them+all%22+
### Iteration 1..N
Goal Date:  
Description: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oskarth** [comment]
Something like https://wiki.ubuntu.com/5-A-Day where "everyone" joins every so often and fix bugs. Make it a bit competitive and open to rest of community in terms of hunting. Swarm support this activity and make it a regular and exciting thing. Requires: QA, community, possibly marketing.

**Comment by oskarth** [comment]
@annadanchenko Are there any high-priority (grandma) bugs that are currently not bountied up? If so, why not?
