### ISSUE TITLE
Improve status-go release process

### ISSUE THREAD

**Issue by adambabik** [status-im/ideas#52]
## Preamble

    Idea: DEV#52
    Title: Improve status-go release process
    Status: Draft
    Created: 2017-11-29

## Summary
[status-go](https://github.com/status-im/status-go) is being consumed by more and more projects like [status-react](https://github.com/status-im/status-react) and status-desktop. We also create libraries that wrap status-go like [status-nodejs](https://github.com/status-im/status-nodejs) or React Native modules embedded in [status-react](https://github.com/status-im/status-react). 

The goal of this idea is to improve status-go release process and allow other projects to safely depend on status-go.

## Vision
There are a lot of problems with how status-go is released now:
1. All work happens on `develop` branch,
1. There is no stable branch like `master`,
1. There is neither semver versioning nor tags to mark individual releases,
1. There are no binaries easily available for various platforms.

The vision here is that the release process is automated and its outcome is a new git tag, changelog on [Releases page](https://github.com/status-im/status-go/releases) and binaries for iOS, Android and node.js (linux and macOS oses).

Also, any code in `master` branch should be considered safe, i.e. it should pass all tests, including e2e tests on public networks. `master` could be considered also as `latest` release. (TBD, we may not need this at all.) 

This could be also really helpful for bug reporting (especially, if we want to use SOB for bug reports in the future) and Test Team as it's often unknown, until further analysis, which status-go version (currently git SHA) is used by the current Status app build. 

Finally, it's something that may bring more external contributors as the project will be better managed and organized.

## Swarm Participants
I think two contributors is enough. It's hard to split the work here between more developers.

- Lead Contributor: @adambabik
- Testing & Evaluation: TBD
- Contributor: TBD

## Requirements
1. This idea will need a hosting as status-go binaries, especially for iOS, are pretty large (around 80-90MB). There is a way to add files to the releases on Github and it should be researched first. If it's not a viable solution, we should use some hosting like S3.

### Minimum Viable Product
Introduce an automated way of versioning and concept of release branches. It's described in details here: https://github.com/status-im/status-go/issues/422.

Goal Date: TBD
Description: Deliverables described in https://github.com/status-im/status-go/issues/422.

### Iteration 1
Each release should contain binaries for the following platforms:
- Android (`.aar` library),
- iOS (framework),
- C-archive for Linux ([status-nodejs](https://github.com/status-im/status-nodejs requirement),
- C-archive for macOS ([status-nodejs](https://github.com/status-im/status-nodejs requirement).

Goal Date: TBD
Description: Binaries on Github or other file hosting provider, easily accessible for other projects.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by adambabik** [comment]
Note: each merge to master (or maybe to a release branch) should open a PR in status-react so that we can get feedback faster if anything wrong is with status-go.

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
