### ISSUE TITLE
Dapp Division 

### ISSUE THREAD

**Issue by thisbejim** [status-im/ideas#56]
## Preamble

    Idea: <to be assigned>
    Title: <title>
    Status: <Draft | In Progress | Closed >
    Created: <date created on, in ISO 8601 (yyyy-mm-dd) format>
    Requires (*optional): <Idea number(s)>
    Replaces (*optional): <Idea number(s)>

## Summary

The dApp Division's purpose is to improve the dApp experience on Status through curation and partnerships, R&D, education, and the funding of external development projects.

### Curation and partnerships
Eventually we will have community curated dApps, until then we must find the best dApps out there and work with their creators to make those experiences "Status ready". 

### R&D
We should continuously work to improve the dApp experience on Status. An example R&D project that has already been discussed is bringing fullscreen native dApps to status that work best outside of a chat context.

### Education
Developers should start building new projects with Status in mind. Education is key to ensuring the best experiences possible. Clear, in-depth tutorials and documentation is the goal here.

### Funding external development projects
We will set up an "X-Prize" like community voting platform to help fund new and innovative dApp ideas that will provide value to both the wider Ethereum community and the Status platform.

## Swarm Participants

- Lead Contributor: 
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- PM: 
- UX (if relevant): 

### Minimum Viable Product

Goal Date:  

Description: 

## Dates
Goal Date:  

Description: 

Testing Days required: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by divan** [comment]
@thisbejim I have a dApp idea that I would love to implement and document the process. Does it fall under this idea?

**Comment by thisbejim** [comment]
@divan Yeah definitely! I'm unsure if there would be a community voting mechanism to decide what we build or not though, that's up for discussion. It might just be that the swarm votes on what to build at first and we go from there. Documentation of the process would be a big part of it as well to help educate new developers entering the ecosystem.

**Comment by noman-land** [comment]
I'm interested in contributing to this as well. I think Status needs some fun things to do once you get inside the app. Especially fun things that show off the p2p tech. Also, documenting and demystifying how to make "full stack" dapps is invaluable at such an early stage. 

I have experience writing React/ES6 frontend and have written some Solidity contracts as well.

**Comment by pablanopete** [comment]
I totally can contribute ~10 Hours to this swarm and lead some initiative once the new year starts and there are a few less things to juggle. 

Would love to see SNT carbon voting part of this.

**Comment by thisbejim** [comment]
Fantastic! Would be great to kick something off in the new year if we can gather a few more to the swarm. Sounds like building out a SNT voting platform could be an option for the first dapp.

**Comment by jarradh** [comment]
Yep I think this is a great idea @thisbejim
