### ISSUE TITLE
Use Mainnet as the default network

### ISSUE THREAD

**Issue by chadyj** [status-im/ideas#58]
## Preamble

    Idea: 58-mainnet-default
    Title: Use Mainnet as the default network
    Status: In progress
    Created: 2017-12-08

## Summary
Alpha builds of Status should default to Mainnet. We should be using Status in a real-world environment.

## Swarm Participants

- Lead Contributor: @adambabik
- Testing & Evaluation: 
- Contributor: @themue
- Contributor: 
- PM: @chadyj 
- UX (if relevant): 

## Product Overview

Currently the Status alpha builds use testnet, but using Mainnet is a key milestone for the public launch of Status. There will be potentially be major performance and security implications so these issues should be surfaced as soon as possible so the app can be tested in a real-world environment. 

From a users perspective, Mainnet should be used as it is required by most popular DApps, and is needed for real transactions, so the full potential of Status can't be seen until we switch.

## Product Description

Security and performance should should be discussed and considered.

Also, several Dapps should be tested. 

## Minimum Viable Product

**This MVP does not mean that after it's finished we deploy the app with Mainnet enabled by default but defines prerequisites that should be done before we consider doing so.**

Goal Date: 2018-04-06

1. [ ] Development of required components is done. The work is tracked here: https://github.com/orgs/status-im/projects/15,
1. [ ] There is a Status App build with mainnet available,
1. [ ] All components have been tested by the Q&A Team.

## Audit iteration

Goal Date: 2018-04-20 (?)

1. [ ] Security audit is finished by an independent company,
1. [ ] The final report is available,
1. [ ] All reported security issues are evaluated and fixed.

## Marketing iteration

Goal Date: 2018-04-??

1. [ ] Status App Bug Bounty program is announced and will last for at least X weeks.

## Success Criteria

1. Mainnet is operational just like testnets. It's possible to select it from the Status App profile.
1. The audit is completed with a final readout.
1. There is a blog post with Status App Bug Bounty.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by pablanopete** [comment]
Would love to be part of the dog fooding with this time willing I can pledge ~5hr a week to checking DApp functionality - I’m already working with State of the DApps to an extent to have our DApps that are responsive as well listed on their site with tagged images see - supported by status tag based on a spreadsheet I will reference to their team. https://www.stateofthedapps.com/dapps/gnosis

**Comment by divan** [comment]
@chadyj I'm not sure about "should default to mainnet" part, but we can definitely have custom builds with Mainnet enabled and distribute it inside the core team, so we can test it in a small group first to identify possible problems. What do you think of this approach?

**Comment by chadyj** [comment]
@divan We have to switch sooner or later. In your view what is the point at which we should switch for alpha users?

In the interim I definitely support more internal testing as you suggest.

**Comment by jaehoonyou** [comment]
so [potential of Status can't be seen until we switch.]  when did you push the switch  
i am - 89% coin.

**Comment by adambabik** [comment]
There is a related idea [Wallet compatibility and HD Keys implementation](https://github.com/status-im/ideas/issues/94). HD Keys is a topic that will be closely reviewed during the security audit.

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
