### ISSUE TITLE
Status Open Bounty v2

### ISSUE THREAD

**Issue by arash009** [status-im/ideas#59]
## Preamble

    Idea: #59
    Title: Status Open Bounty v2
    Status: In Progress
    Created: 2017-12-12

## Summary
To further enhance the current capabilities of Status Open Bounty, improve the user interface and increase the amount of information available to first time users.

To achieve this, multiple iterations and releases will delivered, each focusing on increasing capabilities for a target audience. The first two are around features, bug fixes, and changes for developers and organisations:

https://github.com/status-im/open-bounty/projects/1
https://github.com/status-im/open-bounty/projects/2

## Swarm Participants

- Lead Contributor: @arash009
- Testing & Evaluation: @churik 
- Contributor-Smart contracts: @3esmit 
- Contributor: @siphiuel @martinklepsch @andytudhope 
- PM: @arash009
- UX (if relevant): 

## Product Overview

As a developer, I want to search for and find suitable projects that I can contribute to and issues to solve, in a code repository that I am familiar with, and be compensated for my time and expertise, in a suitable form of cryptocurrency.

As a repo maintainer, I want to find a suitable talent to work on my project to help solve a bug or develop a feature, in a code repository that I use, and I am willing to compensated them for their time and expertise, in a suitable form of cryptocurrency.

The goal of SOB v2 is to take SOB from its current state that was built for the initial launch, to a platform that can scale for increasing numbers and complexity.

The 2 projects should be implemented together to maintain balance between number of organisations onboarded and bounties available, with number of developers engaged. so that we dont end up in a situation with a large bulk of bounties that stay open for long periods of time.

### Product Description

Requirements for each of the stories/features are not yet fully defined. An MVP of each to be identified based on swarm participants before implementing. However, the overall goal of the 2 projects is to increase usability of Open Bounty to be able to meet growth and large scale expansion.

### Minimum Viable Product

We will work with our partners in the ecosystem to help develop the features based on continuous feedback and iterative delivery.

Description: 

## Dates
Goal Date: 2018-01-15 

Description: 

Testing Days required: 

## Success Metrics
Qualitative metrics:
- SOB website has sufficient information to easily onboard new developers not familiar with an open source bounty program and/or crypto.
- Onboarding process of organisations is simplified and automated as much as possible, removing dependencies on human interaction.

Quantitative metrics:

Targets by Dec 2018 |  
-- | --
Total active bounties | 10,000
Total active contributors | 5,000
Total businesses onboarded | 500

The goal is to build up a sizable network of contributors, both from the developer community and open source organisations so that SOB become the 'go to' platform for open source bounties.

This will enable SOB at that time to invest in and develop a growth strategy based on community feedback and gaps identified in the market.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by thisbejim** [comment]
I will kick things off here by pledging a focus of 1 (40h/week). Will be collaborating with @3esmit on smart contracts.

**Comment by arash009** [comment]
Thanks @thisbejim for kicking things off. I've assigned everyone else that I think will also contribute into the swarm. If I'm the wrong assumption please let me know.

**Comment by siphiuel** [comment]
My commitment is 40h/week.

**Comment by churik** [comment]
Commitment: 25h/week

**Comment by arash009** [comment]
Commitment: 40h/week

**Comment by martinklepsch** [comment]
Suggesting new exit criteria to wrap up this swarm:

### Exit Criteria

[Bounty Issuer / Org Dashboard](https://github.com/status-im/open-bounty/issues?q=is%3Aissue+is%3Aopen+label%3Aorg-dashboard) is shipped.

Specifically:

- A dashboard for bounty issuers is added
- It shows total spending and open bounties in USD
- It's easy to find bounties that require action and clearly communicated what those actions are

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
