### ISSUE TITLE
Status Workplace Directory in Slack

### ISSUE THREAD

**Issue by naghdy** [status-im/ideas#60]
## Preamble

    Title: Status Workplace Directory in Slack
    Status: Draft
    Created: 2017-12-14

## Summary
This document outlines a tool for the Workspace Directory in Slack, to help answer the question:

> “Who are you, and what are you working on?”

## Swarm Participants
- Lead Contributor: @naghdy
- Contributor: 

## Product Description
While in Slack, the Workplace Directory should show the following information

General Information
- Real Name
- Updated Profile Photo
- Email address
- Start Date
- Current Timezone

Role Specific information:
- Title
- Division (Go, Clojure, QA, DevOps, Smart Contracts, UX, PM, Marketing)
- Active Idea #’s (where relevant)
- Recent updates from Geekbot standups
- Supporting team member
- Team members supporting

### Requirements & Dependancies

- Role specific information is available through the [BambooHR API](https://www.bamboohr.com/api/documentation/), [Geekbot API](https://geekbot.io/developers) and Github.

## Dates
Goal Date:  

Description: 

Testing Days required: 
## Code

https://github.com/status-im/status-workspace-directory

## Success Metrics

- After 4 weeks, 10% of Status Slack daily users check a user profile
- After 12 weeks, 50% of Status Slack daily users check a user profile

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jacqueswww** [comment]
Sounds like something fun to script together, I can pledge to do it - always wanted to do a slack bot ;)

**Comment by naghdy** [comment]
Thanks @jacqueswww for your work. See the current MVP of the directory here:

https://github.com/status-im/status-workspace-directory
