### ISSUE TITLE
Improve and delegate SOB infrastructure and welcome testing environments

### ISSUE THREAD

**Issue by pablodip** [status-im/ideas#70]
## Preamble

If the goal of the bounty is to delegate programming work, why not delegate infrastructure work as well by using external services? :)

Delegating infrastructure work is even easier, since infrastructure is normally generic (generic services), while programming work is normally custom for our domain problem.

    Idea: <to be assigned>
    Title: Improve and delegate SOB infrastructure and welcome testing environments
    Status: Draft
    Created: 2018-01-17

## Summary

Use external services for the SOB infrastructure so that we can delegate that infrastructure, have a more powerful one, and in consequence we can have better tools and more focus to solve our domain problems. As an example of big benefit, it will provide testing environments for QA, that are needed in the SOB.

## Swarm Participants

- Lead Contributor: @pablodip
- Testing & Evaluation: 
- Clojure Contributor: 
- Smart Contract Contributor: 
- PM: 
- UX (if relevant): 

## Product Overview

Using external services for the SOB infrastructure will help with collaboration, maintenance, stability, availability, scalability and testing.

Let's start by reviewing what we have right now.

Right now an installation of the SOB uses this infrastructure:

* A server to run the Clojure system.
* Postgresql as database of the Clojure system.
* An Ethereum node. (Geth right now)
* A place to save logs (the filesystem right now).
* A place to save web sessions (memory right now).

There is a single server as a service right now where we run the production SOB with all its infrastructure, and the SOB for QA, also with all its infrastructure. That has some disadvantages:

* By having a single server, we have limited availability, since it is a single point of failure.
* By having production and develop together, production can get affected by develop.
* By having all infrastructure in the same server, things could get affected by each other.

Also we have to maintain all that infrastructure, which means:

* Keep it running and solve any possible problems it generates.
* Keep it updated.
* Keep the server where it runs also running and updated.

For example, lately there have been problems with the sync of the Ethereum node and with server rebooting.

When using external services, they provide the service and they are responsible to keep it working. That is, if there is a problem, they solve it. If there is an update, they perform it. Offering a reliable and powerful infrastructure is their domain problem. Let's take advantage of that. The same as we do with Github or Gmail for example.

Infrastructure is a byproduct of solving our domain problems. I think we can face that byproduct in a more powerful and less laborious way.

I am going to describe a possible solution for the SOB infrastructure and its advantages with services I know (Heroku and Infura), but suggestions are welcome to use others if they are better.

Let's start.

First need a server to run the Clojure system. Heroku provides containers to run code (https://www.heroku.com/dynos), and these are some of their advantages:

* Isolated: so production would not be polluted with other env like QA, nor with other infrastructure like the database, etc.
* Scalable: you can add more containers easily so we would be able to scale with no additional work. There is even autoscaling. (https://devcenter.heroku.com/articles/scaling)
* Deployment: provide a powerful deployment system, that we can even describe in the very same repo (so with versioning superpowers), easily pluggable for continuous delivery.
* Types of processes: which will allow us separate the containers that serve users from the containers that perform background tasks, so that the background tasks don't affect the user. We have this in the same server and process right now. (https://devcenter.heroku.com/articles/procfile)

We also need a Postgres service. Heroku also offers that, with good features as well, like high availability, backups, fork, etc. (https://devcenter.heroku.com/categories/heroku-postgres)

An Ethereum node is also needed, and for that we can use Infura. (https://infura.io/) Infura offers access to Ethereum through HTTP, with some interesting features: access to several networks, use geth or parity.

An additional benefit of this is that there would be testing environments, so that we could have a testing environment for the pull requests that we want with Heroku Review Apps. (https://devcenter.heroku.com/articles/github-integration-review-apps). That way we would have an environment to test pull requests separately and only merge them when they are ready. So that  we would solve all the complexity we are paying for having the develop branch for that purpose (https://github.com/status-im/open-bounty/issues/212).

Let's review the benefits:

* Collaboration: thanks to describe in the very same repo how the system runs, and to do it with a well documented and expanded tool instead of with an own custom tool. Collaborators would be able to understand how the app runs and contribute to maintain and improve it, as well as running their own instance in Heroku if they want.
* Maintenance: thanks to delegating the maintenance of he services of our infrastructure, we would have more focus for our domain problems.
* Stability: thanks to adding or removing several servers with just one click, we would be able to scale the service when we need it.
* Availability: thanks to not depending on a single server, we would have a more available system.
* Testing: thanks to having testing environments for the pull requests, we would be able to test them in an isolated way, and would improve the git workflow by getting rid of the develop branch.

#### MVP 1: Move the `develop` environment

Goal Date: 2018-02-28

Description

* Make the app work without depending on the filesystem.
* Make the app work without depending on a single server.
* Separate http process from worker in the app.
* Make the app run on Heroku.
* Make sure that everything works find there.
* Set up a subdomain for this new `develop` environment.
* Move the data in the `develop` environment.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by pablodip** [comment]
Would love to know your view on this, @arash009, @v2nek, @dmitryn, @tpatja, @siphiuel, as well as any corrections in the current infrastructure. :)

**Comment by martinklepsch** [comment]
Hey @pablodip I think this is an excellent effort. 👍 

While I'm not a huge fan of Heroku your reasoning is pretty good and it does make a lot of sense in our current situation. Heroku is significantly more expensive than running our own stuff but I believe for the immediate future this is an acceptable tradeoff. (And we likely save on engineering time too.)

One thing I'm uncertain about with Heroku is the question of how easy it would be to "clone" our infrastructure. Stuff like that is nice about [Terraform](https://www.terraform.io/) and similar approaches. As you said however Heroku's Review Apps seem to be an acceptable abstraction over a more general ability to create identical environments.

As for Infura I can't really give much feedback but if it simplifies the setup for newcomers and we don't lose anything important by using it — it's probably a good idea.

✅   from me.

**Comment by siphiuel** [comment]
Infura integration: https://github.com/status-im/open-bounty/issues/302 and associated PR: https://github.com/status-im/open-bounty/pull/303.

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
