### ISSUE TITLE
A/B testing

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/ideas#72]
## Preamble

    Idea: Evaluate opt-in A/B testing opportunities and development effort
    Title: A/B testing
    Status: Draft
    Created: 01/26/2018
 

## Summary
Through A/B testing we can compare variations to the app to understand what copy, layout, visual design performs best in achieving our goals. For example, is public chat used more if we call it 'public chat' or 'channel'. Do people more frequently request a transaction when we call it 'Receive' ir 'Request'.

## Swarm Participants
TBD

- Lead Contributor: TBD
- Testing & Evaluation: TBD
- Contributor: TBD
- UXR: @hesterbruikman

## Product Overview
As designer/developer/researcher/pm, I want to base decisions for copy, visual design, layout on data, because I want to know that what I build is succesful without unnecesary long discussions.
- describe requirements fo A/B testing
- select platform for A/B testing
- Assess development effort
- Implementation

### Product Description
Showing different variations of the app to people who opt-in. At all times, minor variations that don't disrupt the overal flow or functonality of the app.

### Requirements & Dependancies
TBD

### Minimum Viable Product
TBD

## Dates
TBD

## Success Metrics
TBD

## Supporting Role Communication
TBD

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
