### ISSUE TITLE
Move from RealmJS to different persistence technology

### ISSUE THREAD

**Issue by janherich** [status-im/ideas#74]
## Preamble

    Idea: <to be assigned>
    Title: Replace RealmJS
    Status: Draft
    Created: 2018-02-01

## Summary
Explore options how to get rid of RealmJS in `status-react` RN App, pick the most suitable one and perform the necessary changes

## Swarm Participants

- Lead Contributor: @janherich
- Testing & Evaluation: 

## Product Overview
While working with `status-react`, RealmJS was described as a pain-point by multiple developers, especially when data migrations are concerned. The main points were (not necessary in order of importance):

1. Too "heavyweight" for our use-case. While RealmJS performs quite well when compared with many other mobile ready persistence technologies (like SQLite, especially for reads), we don't really need that performance, because our single-source-of-truth is `re-frame` app-db data-model, where all data for business-logic resides and from which queries for UI elements are directly derived.
So we don't need "online" reads from persistence storage at all (in fact, not doing them makes our codes simpler, faster and more functional/idiomatic) and writes doesn't need to be synchronous (blocking) as well, so performance characteristic we truly need are greatly relaxed. 
Realm also provides things like automatic subscriptions on changes in model (not used at all in our app) and generally seems to be more suited for imperative Object-Oriented approaches, where it's the central data point, drives automatic UI redrawing via data-model subscriptions, etc. 

2. Being totally custom solution not based on any adopted standards like SQL, everyone who wants to work with realm needs to learn realm (we can't leverage the fact the SQL is almost universally understood by all software developers) + there are not many resources available when things go wrong, or something not entirely trivial is attempted (more difficult queries, etc.). 
It's the most painful when writing migrations, as some less-standard situations (migrating child objects in parent-child relationship) are super hard to understand + not described anywhere in official docs. 

3. Query language seems very low-level and not at all declarative like for example SQL. Though we probably won't need that really badly (as we don't need "online" reads), inspecting the state of persistent data storage is non trivial, compared to writing succinct SQL queries we are all used to.

4. We can't really inspect the storage state other then in running application by programatically querying  realm db (so in reality on develop build connected to repl). This is very problematic when debugging non-trivial migration problems, where it's essential to be able to inspect data-store before the app is started (and migration performed).
With something like SQLite, or `edn` serialisation, it would be trivial to grab db-dump from any tester device and inspect it , greatly reducing the time to figure out actual problem and fix it. 

### Product Description

Nothing directly visible for end user, but huge productivity boost for developers and testers alike, enabling faster development cycles and feature delivery for end users.

### Requirements & Dependancies
1. Storage technology requirements are identified
2. Viable alternatives are chosen
3. RealmJS is replaced by something addressing all our pain points mentioned above

### Minimum Viable Product

Goal Date: 2018-02-10

Description: Storage requirements are identified, viable alternatives are discussed and some explorative work is done, testing the viability of alternatives (to quickly identify anything which would be essentially blocker for given persistence technology).

## Dates
Goal Date: 2018-03-01 

Description: The best alternative is picked based on common agreement and implemented in code to get rid of the RealmJS.

Testing Days required: As this would be major far reaching change, one week of testing fully focused on the change is realistic estimate.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.

**Comment by janherich** [comment]
I think that the idea is still very much relevant, and easier to implement then ever, now when we moved data access purely to co-effects/effects in `status-im.data-store.*` namespaces.

**Comment by janherich** [comment]
Will be further worked on as PR draft
