### ISSUE TITLE
Fast status UI #55a

### ISSUE THREAD

**Issue by dmitryn** [status-im/ideas#76]
## Preamble

    Idea: tba
    Title: Fast status UI #55a (status-react part)
    Status: In Progress
    Created: 2018-01-24

## Summary

Status app should be fast enough to provide user smooth and nice experience - no lags and UI freezes.

## Swarm Participants

- Lead Contributor: @dmitryn (40h/w) 
- Testing & Evaluation: @Serhy  
- Contributor: @rasom 
- Contributor: @janherich 
- Contributor: @yenda
- Contributor: @mandrigin 
- Contributor: @flexsurfer 
- UX: TBA

## Product Overview

App should be fast from user standpoint - switching screens, sending/receiving messages, dapp browsing. Every UI component should be responsible and provide immediate feedback to the user.

User stories to be resolved:
- https://github.com/status-im/status-react/issues/3108
- https://github.com/status-im/status-react/issues/3095

### Product Description

- use another js thread for heavy/long-running computations
- load realm into app-db on startup and don't do any further unnecessary reads from realm.
- do async writes to realm by using core async buffer
- measure message passing through RN Brigge
- measure re-frame queue perfomance by forking re-frame and adding custom logging
- measure subs and view rendering: make re-frame-trace with re-frisk to use it as measurement tool

### Requirements & Dependancies

Part of https://github.com/status-im/ideas/issues/55
Relates to https://github.com/status-im/ideas/issues/71

### Minimum Viable Product

Goal Date: 2018-02-16. Iteration 2.

Description: 
DONE:
- async realm writes  https://github.com/status-im/status-react/issues/3146
- RN bridge measurement  https://github.com/status-im/status-react/issues/2963
- re-frame queue logging https://github.com/status-im/status-react/issues/3080

IN-PROGRESS:
- another js thread for computations https://github.com/status-im/status-react/issues/3211
- replace reads from realm https://github.com/status-im/status-react/issues/3210

TBD:
- measure subs/views rendering https://github.com/status-im/status-react/issues/3082

## Success Metrics

User tap results in UI reaction <100ms.

## Exit criteria

Perf user stories 1,3,4,5 resolved:
https://github.com/status-im/status-react/issues/3095
https://github.com/status-im/status-react/issues/3108
https://github.com/status-im/status-react/issues/3336
https://github.com/status-im/status-react/issues/3397

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
