### ISSUE TITLE
SOB - Data and Domain Oriented Programming

### ISSUE THREAD

**Issue by pablodip** [status-im/ideas#77]
## Preamble

    Idea: <to be assigned>
    Title: SOB - Data and Domain Oriented Programming
    Status: Draft
    Created: 2018-02-09

## Summary

Software is built to solve domain problems, which need representation in code.

And that representation is one of the biggest difficulties and costs in software, partly because of the problems to be represented, but mainly because of accidental complexity, which is caused by not treating pieces independently, by lack of structure and by natural entropy.

This idea is about defining a structure oriented to data to represent and solve the domain problems in a much more simple way. And about using using it gradually. It will basically have these benefits:

Robustness: it works, and does it as expected.
Understandability: people can know how it works.
Adaptability: it can work differently.
Power: it can solve more complex problems and in a better way.

## Swarm Participants

- Lead Contributor: @pablodip 
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- PM: 
- UX (if relevant): 

## Product Overview

Firstly I am going to explain some concepts to represent better domain problems, then I will explain the power of thinking in data and how it relates to the domain, some examples of leverage with all that, and I will finish with a list of goals for the structure to be defined.

Along the way I will be comparing things with the current situation in the SOB.

#### Modules

Modules are the main divisions of the domain, the biggest groups of pieces.

Benefits:

* Help think in a simpler way by grouping pieces with cohesion.
* Help decouple, since modules only communicate each other through a public interface.
* Allow to understand the main parts of the domain by just having a look at the structure of the code.

Some examples of modules that the SOB could have:

* A module for users, to deal with the register, the profile.
* A module for bounties, to deal with the creation of bounties, the funding, the revokation, the payout.
* A module for github, to deal with accessing, caching, syncing github info.
* A module for marketing, to extract some information.

In the current code there are no boundaries between domain parts, everything can be related with anything in any way, which produces a lot of accidental complexity.

#### Operations

Operations are actions that are performed to solve domain problem, and belong to modules.

For example, creating a bounty is an operation, or registering a user, or reading information about an user.

Benefits:

* Help think of simple and composable actions that help solve the domain problems.
* Allow to understand easier and faster the domain by knowing the actions that can be performed, and also easily read in the code.

Operations are normally executed from two places:

* From other modules.
* From a layer on top of modules, for example from an api or from a webpage, or from a worker.

In the current code domain operations aren't represented or structuted in a certain way, so they mixed with the rest of the pieces.

#### Events

Operations make things happen, and those things that happen and are relavant to the domain are called domain events.

Some examples of things that happen in the SOB that are relevant to the domain: the creation of a bounty, the change of status of a bounty (from new to deployed, or to funded, or to paid), the registration of an user.

Benefits:

* Allow to run other operations in response to some domain events in a decoupled way. For example you can notify users in response of a bounty creation, without the creation knowing anything about that notification.
* Allow to understand what relevant things happen in the domain by just having a look at the code.

In the current situation domain events aren't represented nor operations happen in response of domain events. Actions are just executed where needed, in a coupled way. And that is probably why there are so many code for logs.

#### Models

Models (entities) are the elements of the domain. They normally have an identifier and some attributes.

Some examples of models in the SOB: a user, a bounty, a github issue, an Ethereum contract, a github pull request.

Benefits:

* Help think about what the elements are, what attributes they have, and to do it in a simple and composable way.
* Allow to know what elements the domain has by just looking at the code.

The current situation is that models aren't defined in a certain way, but just there are some uses of information in several places, like the database and the code. And some of those models are coupled, like bounty with github issue and with ethereum contract.

#### Integration

In order for the domain to work, it needs to be integrated to some technical things, like a database, or an ethereum node, or a framework or library.

Some of those integrations are defined by the domain itself, like persisting a bounty, or deploy the contract for a bounty. Those definitions made by the domain are done in an abstract way, so that they can be implemented in any way as long as they comply with the requirements.

Benefits:

* Allow to think and solve first the domain problems, and then the integration ones. And also separately.
* Allow to replace an implementation of an integration without affecting the domain or the integrations of other modules.

The current situation is that the domain and its pieces are coupled and mixed with the integrations. In fact sometimes the domain is solved more in integrations than in the domain itself.

### Data

One of the biggest difficulties when representing problems is the representation of data.

In the end all we do is work with data: we receive data, expect that data to be some certain way, process/save that data, return some data.

And to solve domain problems all we need to do is to represent that data: operation inputs are the data that we can receive, operation outputs are the data that we can return, models are the data that represent a concept in our domain, and domain events are the data that describes facts that happened in the domain.

So if we can orient our thinking, structure and programming round data, it would help a lot.

And we can use a tool to do so that represents very well data in Clojure: spec.

### Leverage

These are some examples of possible leverage, but there are many, since leverage tends to emerge when structuring and composing simple things, and that is precisely what this idea is about.

#### Logs

Right now code of logs is spread everywhere, causing a lot of noise, work, and inconsistency.

With the above domain conceps, just by logging the operations that enter in the system and the domain events that those operations generate we would know a lot what is going on in the system. And could be done in a single place, and only one time, and would serve for any number of operations and domain events.

#### Testing

Right now there are almost no automated tests, just a few isolated ones.

By specifying the data and inputs and outputs of the system, we could have both example and generative testing for the system.

#### Auto-Documentation

Right now it isn't possible to understand the domain and behaviours in the code unless you try to decipher, since everything is mixed.

By using the domain concepts described above anyone could know what the domain is about, what actions happen there and how they are, the same for the elements, and also for events that happen in the domain. The cost of understanding and programming would be much lower, even for ourselves, since structure and order always help cognition.

#### Github Syncronization

This is something that is causing issues right now. To solve this in the current situation more and more behaviour would be needed everywhere, since there are no separation of github access.

With the above domain concepts there could be a module for Github, and the rest of the modules would use it to access any github info, without even knowing if it is in real time, cached, or whatever. And it would be the responsibility of that Github module to keep that data valid and up to date, so it wouldn't affect any other part of the domain, as it is happening now.

### Goals for the structure

* Should define how to represent and structure the above domain concepts, with the domain and integration separated.
* Should define how to represent errors in the domain.
* Should define what things are public and private in the abstractions, like modules or integration.
* Should define how to represent automatic tests, for both domain and integration problems.
* Should work for Clojure and ClojureScript, so that it can be used from the server and client.
* Should define the structure of both the domain in the server and in client to output an interface.
* Should allow to work with reasonable file lengths.
* Should define how to use it gradually with the current code.

### Minimum Viable Product

Goal Date:  

Description: 

## Dates
Goal Date:  

Description: 

Testing Days required: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by martinklepsch** [comment]
I'm new here and so I can't really assess the issues with the existing codebase. That said I think your Modules <> Operations <> Events <> Models topology makes sense. In fact it brought up various memories of systems I've worked on in the past 🙂 

Not being very familiar with the codebase yet this might also be an excellent opportunity to dive in head-first and "touch everything" or at least become aware of all the various different components.

One thing that I believe would be very important before attacking a refactoring like this: **we should have some integration tests that cover core user behaviour.** You mentioned there are very few at this point. 

Also I was wondering: are you intending for this design to be encoded in a library of sorts? From my current perspective it seems like it could be mostly a streamlining with accompanying documentation. Perhaps later on it could be extracted into a library/framework.

**Comment by pablodip** [comment]
@martinklepsch 

Glad you liked the idea! :)

The idea is still a draft. I still probably have to propose the first version of the structure so that we can talk about something more tangible.

I am answering your concerns. :)

> Not being very familiar with the codebase yet this might also be an excellent opportunity to dive in head-first and "touch everything" or at least become aware of all the various different components.

The goal of the idea in the end is to "touch everything", but also to proceed gradually. So at the beginning it will be mostly definition of new structure and location and definition what small part can be structured like that.

> One thing that I believe would be very important before attacking a refactoring like this: we should have some integration tests that cover core user behaviour. You mentioned there are very few at this point.

That reasoning is correct, but reality is a bit tricker, hehe. There are little tests right now probably because testing is hard because things are coupled and because there is no test structure. So writing tests for code that is hard to test and is meant to be replaced might be very frustrating and expensive. To me we could just proceed with tests in the new structure and with QA, which will probably be smoother. Also there are some end-to-end tests in this idea: https://github.com/status-im/ideas/issues/40

> Also I was wondering: are you intending for this design to be encoded in a library of sorts? From my current perspective it seems like it could be mostly a streamlining with accompanying documentation. Perhaps later on it could be extracted into a library/framework.

Was't intending that, since it will be more about structure than about code utilities. But if we end up using some code that we want to make generic and reusable, we could very well do it. It isn't the main goal of the idea though.

**Comment by martinklepsch** [comment]
Hey Pablo,

> So at the beginning it will be mostly definition of new structure and location and definition what small part can be structured like that.

Good point. Still, working on this I'd probably touch more things than "usual" — but who knows 🙂 

>  There are little tests right now probably because testing is hard because things are coupled and because there is no test structure. So writing tests for code that is hard to test and is meant to be replaced might be very frustrating and expensive.

I can see how this is true for unit tests and similar code-level tests but shouldn't we be able to run integration tests relatively easy? I.e. start server and run some webdriver/headless chrome against a defined endpoint? 

> Was't intending that, since it will be more about structure than about code utilities. But if we end up using some code that we want to make generic and reusable, we could very well do it. It isn't the main goal of the idea though.

👍  Priorities

> The idea is still a draft. I still probably have to propose the first version of the structure so that we can talk about something more tangible.

I'm not sure how the process usually works but I found your write-up quite thorough. When you say "propose the first version" does that mean a PR where you transition a part of the code into the new structure or more specific documentation around the approach?

**Comment by pablodip** [comment]
> I can see how this is true for unit tests and similar code-level tests but shouldn't we be able to run integration tests relatively easy? I.e. start server and run some webdriver/headless chrome against a defined endpoint?

That sounds to me like black-box testing, but testing names are quite a crazy thing. :))

And that is exactly what idea https://github.com/status-im/ideas/issues/40 is trying to do, that is why we can benefit a bit from it. :)

> I'm not sure how the process usually works but I found your write-up quite thorough. When you say "propose the first version" does that mean a PR where you transition a part of the code into the new structure or more specific documentation around the approach?

I'm not sure how the process usually works either for an idea like this. :))

When I said "propose the first version", I meant to expose an actual proposal for a structure, since the things that I explained in the idea are just concepts, but there are many details left. And yes, that proposal should come with a PR that has a minimum prototype showing all details in the proposal.

So I think that the best way to start collaborating in this idea is once I expose that first proposal, since then we can start discussing its details and how to start using it in the SOB. What do you think? :)

**Comment by pablodip** [comment]
Oh, forgot to mention something regarding:

>I can see how this is true for unit tests and similar code-level tests but shouldn't we be able to run integration tests relatively easy? I.e. start server and run some webdriver/headless chrome against a defined endpoint?

It's isn't that easy actually, since the system integrates with Github and with Ethereum, so it isn't possible at the moment to create a total local environment. This issue is related to this: https://github.com/status-im/open-bounty/issues/223

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
