### ISSUE TITLE
The Book of Status

### ISSUE THREAD

**Issue by jarradh** [status-im/ideas#78]
## Preamble

    Idea: #78
    Title: The Book of Status
    Status: Draft
    Created: 2018-02-11

## Summary

We don't use the wiki, but we use google docs, so why not instead just have an amalgamation of documents that gets built into one book?

Instead of just being developer documentation or company policies, let's make a living document, where everyone is invited to add whatever they want - we can use this to tell our stories, what we learnt, etc - so it's kind of like an organization 'bible'.

I feel like this has the potential to more meaningful and organic, while at the same time connecting with our current workflow.

We can build it periodically (daily) then you just know to goto https://book.status.im/ or https://book.status.im/book-of-status.odt and you just know you have everything we ever learnt as an organisation

## Swarm Participants

- Lead Contributor: @jarradh
- Lead Contributor: @carlbennetts
- Testing & Evaluation: @naghdy (unconfirmed)
- Contributor: @oskarth (unconfirmed)
- Contributor: @jacqueswww

### Product Description

This is a [Python script](https://github.com/status-im/book.status.im/blob/master/main.py) and [Git repository](https://github.com/status-im/book.status.im), to be run daily, that will download all documents from a [Team Drive](https://drive.google.com/drive/u/0/folders/0AEhafKkWf9UkUk9PVA) in [ODF](https://en.wikipedia.org/wiki/OpenDocument) format, compiling them together into one ODF and presenting it as both a downloadable book and webpage (displayed with [WebODF](http://webodf.org/))

WebODF supports for 'multiplayer notepad', so at a later date, we can create a Whisper service and upload to Swarm backend for live editing of the document directly.

### Minimum Viable Product

Goal Date:  

Description: 

#### Goal Date: 2018-02-11

Description: Basic Script and Site, is already done, but with some issues.

Testing Days required: 0

#### Goal Date: 2018-03-01

Description: Encourage it's use we may utilize Status Everyday, #75 to further the goals.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jarradh** [comment]
WebODF is a rendering library that's all, what's generated is an https://book.status.im/book-of-status.odt

The questions I have for format considerations are:
- Is it open source?
- How does it handle images?
- Does it preserve annotations?
- Can I be a non-technical person and contribute to it (is it WYSIWYG)?
- what support is there in the future for creating a Google Doc like equivalent?

**Comment by jarradh** [comment]
For me ODT is the only format that really satisfies all of these.

Moving away from Google Doc is important, WebODF supports Real-time Collaborative Editing, so we can rapidly build out a clone if Google has issues.

HTML doesn't really support annotations, PDF is proprietary and binary only (at least we can unzip ODT)

Manipulating ODT is just like manipulating a word doc. Advanced word processors exist for a reason.

Also Keep in mind the first hurdle to adopting Mediawiki being text only formatting, alot of developers explicitly complained about this. Dan finally caved and added the WYSWYG editor but by then we had pretty much moved onto Google Doc.

**Comment by jarradh** [comment]
I'm not sure if unified style is a wanted feature either, doesn't sound very organic to me to impose that directly (if it gets revised fair enough) but it's impeding writers expression. The point of what we're doing is to put the choice in users hand.

**Comment by martinklepsch** [comment]
OK, I'm clearly lacking context here. I think a "Problem Statement" (i.e. answering "what problem are we solving?" without making any remarks about potential solutions) might help my understanding but I'm fine to retreat from this discussion as well. Don't need to understand everything on my first day I guess  😇

**Comment by andytudhope** [comment]
Would love to be a contributor here: learn some python, get my inner grammar nazi on using open source software and generally write and curate delightful and edifying content 😉

**Comment by themue** [comment]
Looks really interesting. My talk audience and others I'm telling about are really interested in Ethereum when I told them it's more the philosophy of a distributed world. So this would be a nice chapter.

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
