### ISSUE TITLE
Fix discoverable statuses

### ISSUE THREAD

**Issue by goranjovic** [status-im/ideas#8]
## Preamble

    Idea: DEV#008
    Title: Fix discoverable statuses
    Status:  WIP 
    Created: 2017-11-10

## Summary

Fix the way discoverable statuses work.

## Vision

Where we are at the moment:

- status discoveries are partially implemented - it works but with a number of open issues (old statuses are not being replaced by new ones, generally status deletion doesn't work, etc.)

Where we want to be:
- status discoveries are scoped out properly, implemented and working correctly

## Swarm Participants

SWARM_COUNT = 3

- Lead Contributor: @goranjovic (main priority - 40 h/w)
- Testing & Evaluation: @asemiankevich (15 h/w)
- Contributor: TBD
- Contributor: TBD

## Requirements

Currently there is a large mismatch between how statuses should work and how they actually work. This is especially visible if we compare local statuses (without any hashtags) and broadcast statuses (with at least one hashtag). Basically, statuses without hashtags behave like users would expect, but the ones with hashtags behave like a decentralized twitter.

In addition to that there is a number of incorrect or not verified behavior related to status expiration and deletion.

Status discoveries need to comply with the following **constraints**:

1. Statuses without any hashtags are visible to one's immediate contacts, but as a profile field - not in discoveries. (this works already)
2. Statuses with at least  hashtag are broadcast to all contacts, from where they are re-broadcast to all their contacts and so on. (this works already, but without any weighing or ranking)
3. The total number of status discoveries stored in any app storage may not be larger than 1000. If more than that number of new statuses are received, the oldest ones should be deleted.
4. Any user may have at most one status shown in other users' Discover screens. 
5. Whenever a user changes their status from A to B, where B contains hashtags, status B should replace status A on all devices that receive it.
6. Whenever a user changes their status from A to B, where A contains hashtags and B does not, there should be a special "delete" status broadcast to all recipients instructing their apps to delete status A.

In addition to that, we should enhance the way that statuses are re-broadcast to transitive contacts to include a weight based algorithm that ranks them based on:

- the newest available information (latest status from that user),
- the most seen contact statuses by other contacts. (that user who has seen the same contact status from all his contacts)
- and actual interactions with contacts, favor contacts that the user has actually messaged themselves.
- if contact is online

Successful implementation of the constraints listed above will result with Discover being in a consistent state where the mismatch between the perception of how it should work and actual implementation largely bridged. That is the must-have list.

Nice to have list contains all the different criteria that may be used in the weighing algorithm.

### Minimum Viable Product
 
- Deletion of statuses on a 1000th item mark fixed and covered with automated cljs tests (constraint 3)
- Statuses with hashtags overwrite any previous statuses from the same user (constraints 4 and 5)

Nice to haves:
- If user replaces a status with hashtags for a status without hashtags, the old status should be removed from any devices who get notified of the change (constraint 6)

Goal Date: TBD
Description: TBD

### Iteration 1 
Goal Date: 
Description: Working MVP

### Iteration 2
Goal Date:
Description: All constraints fulfilled, basic weighing algorithm working (not all criteria)

### Iteration 3
Goal Date:
Description: Working weighing algorithm

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by asemiankevich** [comment]
I pledge focus of 15h/week for Testing & Evaluation

**Comment by goranjovic** [comment]
I pledge focus of 1 - 40h/w for development

**Comment by asemiankevich** [comment]
Here is the list of issues relates to Discover:Statuses : 
https://github.com/status-im/status-react/issues/436 - this is a seaparate idea 
https://github.com/status-im/status-react/issues/696 - closed
https://github.com/status-im/status-react/issues/2308
https://github.com/status-im/status-react/issues/2317
https://github.com/status-im/status-react/issues/2281

**Comment by jeluard** [comment]
I pledge focus 20h/week starting end of next week.

**Comment by naghdy** [comment]
This is an interesting idea. I have a few questions:
1. As a friend/contact of person A, where would I see their Status in my app?
2. What is the user journey that we expect people to take to update their Status. Is it in the short form content, e.g. "I'm at the gym!" or more long form "Here is a new blog post". i.e. are we going for Twitter-esque, or FB-esque rants?
3. How often do we expect users to update their Status? WhatsApp has 'status', and after a user first downloads the app, I haven't seen anyone ever change it. Similar to Telegram. I guess this relates to [1], because unless Person B has a News Feed to see all their friends 'status updates', Person A has no reason to update their status.

**Comment by naghdy** [comment]
Closing due to lack of development for ~10 weeks. We can re-open and use some of the ideas from this swarm when we try and tackle this later.
