### ISSUE TITLE
Onboarding

### ISSUE THREAD

**Issue by andmironov** [status-im/ideas#80]
## Preamble

    Idea: 80
    Title: Onboarding
    Status: In Progress
    Created: 2018-01-25

## Summary
Design and implement a smooth onboarding experience for the Status app. This includes a basic account set up, empty states of the screens and an “educational layer” to explain commonly unclear concepts and possible misconceptions.

## Swarm Participants

- Lead Contributor: @andmironov
- Lead developer: @flexsurfer
- Testing & Evaluation: @anna, @yevh-berdnyk
- PM: @chadyj
- UX: @hester
- UX: @ricardo

## Product Overview
This project is about creating an onboarding experience for the users. Not only setting up an account, but introducing the app functionality and explaining how to benefit from it.

### Iteration 1.  MVP
Goal Date: MVP Launch

A simple and straightforward path from a fresh start of the app to sending a transaction. Basic empty states and basic educational layer.

**Entry points:**
- Fresh start
User for some reason decided to download and install Status from the App Store/Play Store

**Goals:**
- Be able to set up an account and send a transaction

**Roadmap:** 
- *Research & Brainstorm, Date: 2018-02-09* 
  - Define a Persona
  - Define the entry points
  - Define the user goals
  - Define the flows
  - Define the language and general tone of voice
- *Wireframing, Date: 2018-02-12* 
  - Signup flow
  - Recover access flow
  - Login flow
  - Empty states
  - Set up backup and signing phrase
- *Development, Date: 2018-03-01* 
  - Final IOS Mockups
  - Final Android Mockups
  - Technical implementation
  - Graphic Assets (Illustrations and Icons)
  - Play Store/App Store screens and icons
  - Copywriting

### Iteration 2. Tests & Improvements
Goal Date: 2018-04-01

Test and evaluate the work made in iteration 2. Cover more entry points.

**Entry points:**
- Invite from a friend
User gets an invite link via email/message from a friend who already uses Status and wishes to chat with that user

- Transaction request
User gets an invite link via email/message from a friend who already uses Status and requests a transaction from that user

- Invitation to a group chat
- Invitation to public channel

**Goals:**
- Be able to set up an account and start a secure chat with an invite link
- Be able to set up an account and send a transaction to the person who requested it

**Roadmap:**
- *Test sessions, Date: 2018-02-22*
Set up a test session of the onboarding MVP prototype with actual users in a UX lab to gather feedback & insights for further improvements. After the test sessions will be finished, we would structure and document the feedback from users

- *Brainstorm and create wireframes for the new entry points*

## Success Metrics
Reaching the goals we set for the entry points

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by andmironov** [comment]
Finished the Research & Brainstorming of the Iteration 1. Main points:
- Get rid of console as a part of onboarding
- Defined Entry Points. Focused on the "Fresh Strat" for the MVP
- Moved the Seed Phrase Backup to Profile. Moved the Signing Phrase to Wallet Setup
- Added "Advanced" menu items to Profile
- Updated the Log in flow
- Renamed and updated the "Recover Access"

Updated the onboarding prototype here https://invis.io/MJFOBUUTFE4#/272963872_IOS_Signup_01

**Comment by andmironov** [comment]
Put together the main flows:

**Comment by andmironov** [comment]
Started uploading screen to Zeplin here started adding screens to Zeplin here zpl://screen?sid=5a8711ba690d3bba6c2a35b4&pid=5a55d587ba304eed4d2c942f

**Comment by andmironov** [comment]
UPD
As well as the onboarding updates, we should:
1. Update the App icons doe IOS and Android (update background color of the icon and replace the symbol) 
2. Prep up UI screenshots for the App Store/ Play Store

This is the sample text we got from the marketing team:
>Status is a SuperApp. To understand what a SuperApp is, picture if all the apps you used on a daily basis were bundled together into one interoperable app, expressed in an single, chat-based interface - and there you have it. In short, Status is a new kind of tool, for a new kind of Internet.

>Built on top of Ethereum’s public blockchain, Status’ superpower comes from being more than just the sum of its parts. By having communications, financial transactions, and a growing number of decentralized apps and services - referred to as DApps - integrated into just one experience, Status offers its users a revolutionary tool to harness the power and promise of the decentralized Web, right from your phone.

Will be working on these on this week @j-zerah please let us know if there are any updates, specific things we should consider

**Comment by andmironov** [comment]
Plans for iteration #2:


**Introduce Touch ID/Face ID with a PIN code fallback**
By adding this we will be able to solve several problems:
- Encourage more secure passwords by not forcing users to enter a password to sign a transaction;
- Get rid of the signing phrase as a confusing concept;

**Improve the Welcome screen/Empty Home screen/New screen relations**
- Make the welcome screen more representative of shat the app can do.
- Improve the "New" screen, maybe my dividing it into two screens: "New Chat" and "Open DApp"

**Improve the account recovery flow**
Currently, the password is required along with the seed phrase to recover an account.

**Improve the "Backup seed phrase" flow**
- Make it easier to check the correctness of the seedphase
- Maybe show the Seed Phrase when Touch ID/PIN verified

**Improve the copy and tone of voice**
- Approach main concepts from a positive way;
- Add more explanatory screens when something important happens. Consider more misconceptions (why no 2FA?, why no email/phone number? why you can't restore account if lost? etc.);
- Research and rename if necessary main blockchain-specific terms (i.e "Seed Phrase") to match the industry standards;
- Explain more in general (What is a Dapp?, What's a key? etc.)
- Consider having a "Educational" section somewhere in the app or at least on the website

**Consider accepting a contact before chatting**
This is a common pattern, people expect this as we found out during our test session. Also, since the chat is peer-to-peer, an exchange of keys takes place and accepting/declining here makes sense. We can also use this new flow to emphasize the tech side of things and the security and provacy we offer 

**Add animations to illustrations and images**

**Comment by hesterbruikman** [comment]
This is a great list of ideas/to do list @andmironov !

**Comment by andmironov** [comment]
Moved the discussion to https://github.com/status-im/ideas/blob/master/ideas/80-onboarding.md
