### ISSUE TITLE
Research Coordination

### ISSUE THREAD

**Issue by themue** [status-im/ideas#81]
## Preamble

    Idea: #81
    Title: Research Coordination
    Status: Draft
    Created: 2018-02-14

## Summary

Status runs multiple research projects to improve the own code as well as the code our product is based on. Parts are for example **LES/2**, **Whisper**, or a **Light Swarm Client**. They will have their individual swarms and manage their issues in the according repositories or forks.

Documentation is maintained in our [wiki](https://wiki.status.im/Research).

Task of this swarm is to coordinate all reasearch projects, their priorisation, and their documentation.

## Swarm Participants

- Lead Contributor: @themue
- Lead Contributor: @JekaMas 
- Lead Contributor: @adambabik 
- Testing & Evaluation: *open*

### Product Description

The swarm maintains

- a list of all research projects,
- the lead contributors assigned,
- a link to the documentation.

### Requirements & Dependancies

- #71 (Fast messaging)
- #76 (Fast Status UI)

### Minimum Viable Product

Goal Date:  

Description: 

## Dates

Goal Date:  

Description: 

Testing Days required: 

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by jarradh** [comment]
This seems entirely meaningless.
