### ISSUE TITLE
100% Reliable Messaging Experience.

### ISSUE THREAD

**Issue by annadanchenko** [status-im/ideas#82]
## Preamble

    Idea: 82
    Title: Reliable messages
    Status: Draft
    Created: 2018-02-18

## Summary

#75 dialogues clearly show that not every message is delivered to the recipient. In addition, delivered messages sometimes are shown in the other order than were sent. It's one of the core features for the messenger, so Status should deliver all messages in the proper order. If not then we should be able to monitor/capture logs to investigate the causes and fix them.

## Swarm Participants

- Lead Contributor: @oskarth 
- Lead Contributor: @divan 
- Lead Contributor: @naghdy 
- Lead Contributor: @chadyj  
- Testing & Evaluation: @annadanchenko
- Contributor: 
- Contributor: 
- PM: 
- UX (if relevant): 

### Minimum Viable Product

Goal Date:  

Description: 
- [ ] List of the GH issues with exact scenario when messages are not delivered with geth and TF logs. 
- Identify what can be improved for monitoring and investigating issues with messaging. List tools/features for Status messaging monitoring.
- [x] Test https://github.com/status-im/status-react/issues/3116 
- [x] Fix https://github.com/status-im/status-react/issues/2699
- [ ] Fix https://github.com/status-im/status-react/issues/3124

## Dates
Goal Date: 2018-03-06  

Description: 
100% Reliable Messaging Experience before BKK Offsite.

Testing Days required: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by dshulyak** [comment]
i pledge 30h a week to work on this idea

**Comment by oskarth** [comment]
Not well-defined. Closing - superseded by https://github.com/status-im/ideas/issues/99 and others.
