### ISSUE TITLE
Energy Efficient Status

### ISSUE THREAD

**Issue by mandrigin** [status-im/ideas#83]
## Preamble

    Idea: 83
    Title: Energy Efficient Status
    Status: In Progress
    Created: 2018-02-19

## Summary
A specific issue about the energy efficiency of different parts of Status (`status-go`, `status-react`, `desktop` (when running on a laptop battery).

## Swarm Participants

- Lead Contributor: @mandrigin (~25h)
- Contributor (Go): @feuGeneA 
- Contributor (QA): @lukaszfryc (~10h/week)

## Product Overview
Energy consumption is a crucial part of the mobile experience, and even though it is related to performance, it is worth having a separate.
The end goal is:
- to provide a toolkit and guidelines to test energy efficiency of different parts of an app on different platforms;
- using this toolkit to fix the top battery drainers;
- notice regressions early by having tests in place.

### Goals

1. Create a BoK for Energy efficiency testing: https://github.com/orgs/status-im/projects/18
a. test apps are created for both Android and iOS
b. test cases are written and tools are created to measure the energy efficiency of both Status client (status-react+status-go) and tests apps (status-go exclusively).
c. tests are run on a regular basis
d. (stretch goal) tests are automated for both platforms

2. Fix obvious issues with energy consumption
https://github.com/orgs/status-im/projects/17

## Exit criteria
- We have test cases and tools to check the energy efficiency of `status-go` and `status-react` independently;
- We can notice regressions/improvements caused, e.g. by updating the version of `go-ethereum` or new features of Status;
- Top energy draining issues are identified and fixed.

## Success Metrics
KR: 
(1) foreground energy consumption is < 120% of the apps in a similar class (messengers) 
(2) background energy consumption is < 120% of the apps in a similar class (messengers)

## MVP(s)
MVP1 (docs & process): Create and integrate energy efficiency testing as a part of the release process (date: *Mar, 30*)
MVP2 (development): Create a low-power background mode for status-go (date: *Mar, 30*)

## Useful Links
https://github.com/dgryski/go-perfbook

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by mandrigin** [comment]
Since I've already started on https://github.com/status-im/status-go/issues/633, I'll put it to "in-progress"

**Comment by mandrigin** [comment]
That is exactly the pattern I see in our code: https://developer.apple.com/library/content/documentation/Performance/Conceptual/EnergyGuide-iOS/EnergyandNetworking.html

Let me see what we can do with it...

**Comment by mandrigin** [comment]
One more observation is that `discv5` is CPU intensive for some reason.

**Comment by dshulyak** [comment]
@mandrigin good observation regarding discv5, we are not using v5 and discovery in general. But it is enabled by default in p2p.Config

**Comment by mandrigin** [comment]
Because of [the tradeoff](https://github.com/mandrigin/status-go-n-wrapper#22-the-tradeoff) between real-time communications and efficient energy usage, we can't really optimize much when the app is in the foreground.
What we can do, is to optimize the background usage, so on Android, the node doesn't consume that much energy when being in background.

**Comment by mandrigin** [comment]
Next steps for what's relatively easy to fix.

**1. Put the node into some low-power mode when the app is in background**
- [ ] implement APIs to listen to the app state changes in status-go (https://github.com/status-im/status-go/issues/734)
- [ ] use the APIs on status-react side to get these changes
- [ ] implement low-power mode for a node (options there: pause a node, pause networking or make networking sync more rate)

**2. Make Energy Testing Body of Knowledge**
- [ ] move the BoK repo to status organization
- [ ] write a guide to test status-go on iOS
- [ ] write a guide to test Status on iOS

**Comment by lukaszfryc** [comment]
I can contribute ~10h / week

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
