### ISSUE TITLE
Add Lookback to iOS for UX testing

### ISSUE THREAD

**Issue by hesterbruikman** [status-im/ideas#85]
## Preamble
    Idea: @hester
    Title: Add Lookback to iOS for UX testing
    Status: <Draft | In Progress | Closed >
    Created: 22/02/2018

## Summary
We need to understand how people use Status beta. What people say is not always reliable so we want a number of people to show what they do. We can use Lookback.io to record this. (ONLY when people sign up in exchange for SNT). For Lookback.io to work independently, it needs:
- an iOS SDK integrated:
http://help.lookback.io/installing-the-ios-sdk/overview-of-the-ios-sdk
- 3 lines of code to configure: http://help.lookback.io/installing-the-ios-sdk/configuring-lookback/configuring-lookback-participate

## Swarm Participants
- Lead Contributor: @hester
- Testing & Evaluation: @
- Contributor: 
- PM: @chadyj 

## Product Overview
As Status I want to learn how people use the app in order to improve it.

### Product Description
Adding functionality to use Lookback in order to ask participants, who actively sign up for this, record their use.

### Minimum Viable Product
Goal Date: 2018-03-16

Deliverables:
- SDK implemented
- Configuration code added

## Dates
Goal Date: 2018-03-16

Testing Days required: 1

## Success Metrics
We receive recordings of people using the app.

## Supporting Role Communication
Recruitment and configuration of project in Lookback should be followed up by UXR and Marketing.

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
