### ISSUE TITLE
Push Notifications v2

### ISSUE THREAD

**Issue by PombeirP** [status-im/ideas#86]
## Preamble

    Idea: 86
    Title: Push Notifications v2
    Status: Draft
    Created: 2018-03-01
    Requires: #75, #76

**Currently collecting feedback at https://docs.google.com/document/d/1qZ3Vc_AFI5LX2wXSOz9nAkvcqIeoZqNew8-Ottq9LQg/edit#**

## Summary

The current push notification system is sort of in a MVP stage. It works, but there are lots of important improvements that should be done in order to meet basic expectations from end users. Namely, the user expects push notifications to be reliable and helpful while maintaining security. A number of common behaviors illustrate these qualities:
- Reliable:
  - A user expects that he will receive a notification in case he receives a message, should his screen be turned off, or the app be in the background. He also expects that his conversation partners will be notified in a timely manner.
  - A user expects that the notifications he finds on his device accurately reflect unread messages.
- Helpful:
  - A user expects that the notifications he finds on his device accurately reflect unread messages. If he has browsed through a conversation that included messages mentioned in a PN, the PN should be updated accordingly, so the user is not mislead and can actually trust the notification system.
  - A user expects to be able to see message details from notifications without needing to open the app (perhaps configurable due to privacy concerns?).
  - A user expects to be able to be able to ping other users selectively user `@`-type addressing (individual and group notifications), in order to reduce unnecessary noise.
- Secure:
  - A user expects that by receiving PNs, he is not giving up the degrees of anonymity and plausible deniability which are afforded by the app's underlying communication protocol.

## Swarm Participants

- Lead Contributor: @PombeirP
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- PM: 
- UX (if relevant): 

### Requirements & Dependencies

- https://github.com/status-im/status-react/issues/3451: Preview notifications using background app refresh
- https://github.com/status-im/status-react/issues/3487: Notifications about previous messages should disappear when chat is opened

### Minimum Viable Product

Goal Date:  

Description: 

## Dates
Goal Date:  

Description: 

Testing Days required: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oskarth** [comment]
Replaced by https://github.com/status-im/ideas/pull/119
