### ISSUE TITLE
DApp Experience

### ISSUE THREAD

**Issue by goranjovic** [status-im/ideas#88]
# Preamble

    Idea: 88
    Title: DApp Experience
    Status: Draft
    Created: 2018-03-12

See: [88-dapp-experience.md](https://github.com/status-im/ideas/blob/dapp-catalog/ideas/88-dapp-experience.md)

**Comment by liuxiaopai** [comment]
3.Perform some research o existing dapps for better understanding. 
http://dappinsight.com would be a better choose.

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
