### ISSUE TITLE
Interacting emojis

### ISSUE THREAD

**Issue by annadanchenko** [status-im/ideas#93]
## Preamble

    Idea: 93
    Title: Interacting emojis
    Status: Draft
    Created: 2018-03-13

## Summary

Emojis that interact with each other in the chat based on the selected "mood". 

Example: I'm sending a mouse and select its mood as "angry". Recipient can see a mouse in the chat but does not know its mood yet. She sends a cat to the chat with "sleepy" mood. As a result, mouse starts running around sleeping cat and trying to bite it.

## Swarm Participants

- Lead Contributor: @annadanchenko
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- PM: 
- UX (if relevant): @hesterbruikman ? @nikitalukianov ?

## Product Overview

Emojis that can interact in the chat based on their defined "mood". This is a short "cartoon" with several actors who repeat same actions in the chat screen. In future, extra "moods" that define some emojis' behaviour can be purchased with SNT. 
It's not a game but new layer of communication where pictures are interacting in the chat based on our initial input (mood selection).

### Product Description

Functionality: possibility to select emoji, its mood and send it to the chat. Possibility to show "moving" emoji in the chat screen. Possibility to stop/remove sent emoji, so it stops moving on the screen.
Why is this important: it's fun

### Requirements & Dependencies

Mockups from design team and prototype is needed. As soon as it's done we can test with users and later implement it as a DApp or possibly in the chat

### Minimum Viable Product

Goal Date: 2018-04-25

Description: 
User stories described
Design Mockup is ready that can be used for development

## Dates
Goal Date:  

Description: 

Testing Days required: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
