### ISSUE TITLE
Wallet compatibility

### ISSUE THREAD

**Issue by pilu** [status-im/ideas#94]
## Preamble

    Idea: 94
    Title: Wallet compatibility
    Status: in progress
    Created: 2018-03-20
    Started: 2018-03-22
    Requires : 

## Summary

Make Status wallet compatible with the standards described in [BIP39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki), [BIP32](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki), and [BIP44](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki).

## Swarm Participants

- Lead Contributor: @pilu (Andrea Franz)
- Testing & Evaluation: @asemiankevich
- Contributor: 
- Contributor: 
- PM: 
- UX (if relevant): 

## Product Overview

As a user, I want to be able to create an account in Status, and open it in MyEtherWallet and MyCrypto. 

To do this we should update the code that generates our extended keys to follow BIPs 39/32/44.

#### Steps

1. Update the salt used to generate the seed  from `status-im` to `mnemonic`, following `BIP39`. 
2. Update the hmac key to `"Bitcoin seed"` following `BIP32`.
3. Check comments at https://github.com/status-im/status-go/blob/develop/extkeys/hdkey.go#L42.

After doing this, we should be able to import a Status account in MyEtherWallet and MyCrypto using the 12 mnemonic words and the passphrase

Implemented with PR https://github.com/status-im/status-go/pull/783

**Pros**

* Ability to use a Status account in other wallets

**Cons**

* **IT WILL BE IMPOSSIBLE TO RECOVER ACCOUNTS GENERATED BEFORE THIS CHANGE, BECAUSE THE SEED GENERATED WITH THE MNEMONIC WORDS WILL BE DIFFERENT**

### Requirements & Dependencies

Users of the alpha version must know that their current accounts won't be recoverable. 

### Minimum Viable Product

Goal Date:  

Description: 

I can create a new account in Status and open it in MyEtherWallet/MyCrypto using my 12 mnemonic words and password.

## Dates
Goal Date:  

Description: 

Testing Days required: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by JekaMas** [comment]
@pilu Does it relates to https://github.com/status-im/ideas/issues/84 ?

**Comment by pilu** [comment]
@JekaMas no I think they are 2 different developments. #84 is more around saving something (username, avatar, contacts) in whisper. 
This idea is instead around the way we generate the private key starting from the 12 mnemonic words.

**Comment by yenda** [comment]
This seems like a good idea, however since allusers will need to recreate their accounts, I suggest that we include it in a release that does all the breaking changes ?

**Comment by chadyj** [comment]
> This seems like a good idea, however since allusers will need to recreate their accounts, I suggest that we include it in a release that does all the breaking changes ?

IMO do this anytime in alpha (so long as we communicate it properly).

**Comment by pilu** [comment]
@yenda yes we can do it in a special release in alpha as @chadyj said so that users can understand better

**Comment by pilu** [comment]
I also think there will be more work in the UI to explain these things. and maybe we could have both pin/password  and optional mnemonic passpharse. maybe also @andmironov can help us understanding what we need in the UI

**Comment by chadyj** [comment]
@pilu IMO Step 2 should be a different issue as a wallet enhancement.  Doesn't seem to be a blocker for step 1?

**Comment by pilu** [comment]
@chadyj you are right, I can move the second step to another idea. The only issue would be that it would not be compatible with jaxx/metamask because they don't require  a password, but at least it would be ok for MEW/MyCrypto

**Comment by yenda** [comment]
The advantage of not using the combination of seed key and password on top of compatibility with other wallets is that it will make it easier to change the password, I'm always a bit put off by the fact that we currently can't change the password

**Comment by pilu** [comment]
I simplified the idea and removed step 2. I will create a new idea with that part.

**Comment by pilu** [comment]
the beta version of MyCrypto allows now to generate a new wallet with mnemonic words. in the previous versions it generated only a keystore file (but it was possible to import an already existing wallet with mnemonic words).

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
