### ISSUE TITLE
Introduce LES Service Model

### ISSUE THREAD

**Issue by themue** [status-im/ideas#95]
## Preamble

    Idea: #95-les-service-model
    Title: Introduce LES Service Model
    Status: In progress
    Created: 2018-03-20

## Summary

Introduce the LES Service Model where LES clients can subscribe to a higher quality service. Different
payment models will be available, the selection of the full node provider is intended.

## Swarm Participants

- Lead Contributor: @themue
- Testing & Evaluation:
- Contributor: @jeka
- Contributor: @b00ris
- PM: @zsfelfoldi (external)
- UX (if relevant):

## Product Overview

Today all light clients are treated equal by the full nodes they connect. A future service model will introduce the separation between free and payed services. As outlined by Felföldi Zsolt:

- LES will be available either as free or paid service,
- paid service can guarantee availability and short response times,
- client bandwidth demand fluctuates with time, good service quality requires reserve capacity,
- for-profit LES servers can still give away their extra capacity for free (with lower priority than paid service),
- free service is a good indicator of high bandwidth capacity and therefore the capability to provide good service, and
- paying clients will prefer servers which already gave them free service so free service can act as an advertisement.

See https://github.com/zsfelfoldi/ethereum-docs/blob/master/les/service_model.md.

Once the service model is introduced changes to Status app are needed:

- Search of available provides in market place
- Choosing of provider and free usage or selecting offered subscription

For Status it also could become interesting to become a service provider offering payed full node services not only for own clients. This business case has to be evaluated.

### Product Description

Parts of the introduction of the LES Service Model are:

- research, definition, and implementation of connection management system of paying clients for full nodes,
- research, definition, and implementation of payment methods and models,
- implementation of smart contracts for transactions based on the subscriptions,
- research, definition, and implementation of market places for full node providers inclusive a review system, and
- documentation.

### Minimum Viable Product

Goal Date: TBD

Description:

- [ ] New Ultra Light Client Mode is added to LES
- [ ] Ability for client to choose between free and standard payed priority service
- [ ] Seperation of free and payed service on full node
- [ ] Booking of micropayment fees for subscribed standard payed priority service

Outline of MVP and next milestones is currently under discussion.

## Success Metrics

TBD

## Copyright

Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
