### ISSUE TITLE
No merge for a PR if end-to-end tests failed

### ISSUE THREAD

**Issue by yevh-berdnyk** [status-im/ideas#97]
## Preamble

    Idea: 97
    Title: No merge for a PR if end-to-end tests failed
    Status: Draft
    Created: 2018-03-21

## Swarm Participants

- Lead Contributor: @yevh-berdnyk
- Testing & Evaluation: 
- Contributor: 
- Contributor: 
- PM: 
- UX (if relevant): 

### Minimum Viable Product

Goal Date:  

Description: 

## Dates
Goal Date:  

Description: 

Testing Days required: 

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
