### ISSUE TITLE
Confidence in Messaging

### ISSUE THREAD

**Issue by rasom** [status-im/ideas#99]
## Preamble

    Idea: 99
    Title: Confidence in Messaging
    Status: Draft
    Created: 2018-03-22

## Summary
As end users we currently don't have confidence that messages are being sent, delivered and read. This swarm aims to address this.

## Swarm Participants

- Author: @oskarth 
- Lead Contributor: @rasom
- Testing & Evaluation: 
- Contributor: @cammellos
- Contributor: 
- PM: 
- UX (if relevant): 

## Product Overview

We currently don't have confidence in the reliability of messaging in Status. The reasons for this lack of confidence ranges all the way from how 'read' status is displayed in the app, to trivial - and non-trivial - bugs, to bad uptime of critical infrastructure, to how push notifications are decoupled from Whisper messaging, to a fundamental lack of (understanding of) reliability guarantees Whisper protocol provides.

What all these issues have in common is that they cause the end user to not have confidence in their messages being delivered and read. This swarm aims to attack this from a user point of view. It is expected additional swarms might be spawned for more core technical areas as these are identified (e.g. network visibility or push notifications v2).

### Product Description

This section is based on user feedback spawned as part of 75-status-everyday (https://docs.google.com/document/d/1pkfZWxr9I0AqidEuOfogzxEXrcg6ofs2bUkh-HSKD6o/edit)

1. Messages should always be sent.

    a. Generally: lack of trust in messages being sent
    b. Provide better feedback of when messages are or aren’t sent
    c. Allow re-send of individual messages a la Whatsapp

2. Messages are in wrong order.

    a. Confirm fixed in 1on1
    b. Make decision re migrations for old messages
    c. Understand and clarify work needed for private group / public (placeholders)
    d. Design: Deal with right order but “message arriving too late” (see sidebar)

3. Messages lack timestamps.

     a. This appears to contribute to a lack of confidence in messaging
     b. Design (then dev): Add this to UI

4. Messages don’t arrive despite being sent, or they arrive late.
    a. Disambiguate offline from mail server node copy
    b. Understand what is needed to make mail server HA
    c. Give user feedback while it is fetching messages (non-instant)
    d. Understand if there are more reasons messages would arrive late

5. Messages should always be delivered, 100% of the time.

    a. Similar to 1 but stronger
    b. What happens if mail server goes down?
    c. Can we implement read/re-send semantics at Whisper level (mailserver)?
    d. Look into how read receipts can be improved
    e. Clarify UI a la Whatsapp double-tick
    f. Consider tracking send/delivered ratio as a metric

6. Offline inboxing not working in public chat.

    a. Clarify perf dependency on smooth-ui swarm
    b. While perf is being worked on, educate user about offline only being 1-1

7. Perception of lack of notifications.
    a. UXR: understand expectation -  for non-contacts? Public chats? in-app?
    b. Separate PN swarm, clarify dependency with this swarm

8. Get notification but nothing visible in app.
    a. PN delivery being decoupled from Whisper delivery, see point 7 above
    b. Clarify dependency on PN v2 swarm and where work done

9. Perception of never received messages from other people.
    a. Investigate if same as filter while offline bug and current limitations
    b. More 7: Investigate non-contact PN possibility
    c. More 7: Public chat PN?
    d. UXR: Understand this problem and perception better

10. Sometimes need to change mail server manually to get messages working.
    a. Make failure of individual mail server apparent and prompt switching
    b. Automated switching?
    c. How ensure no switching is necessary? (HA, see 4)

### Requirements & Dependencies

Request messages history after background: https://github.com/status-im/status-react/pull/3493
New protocol https://github.com/status-im/status-react/pull/3273
https://github.com/status-im/ideas/issues/87

### Minimum Viable Product

Goal Date:  

Description: 

**TBD**
Probably something like: Select subset of above to implement/finish; do initial community check, do design basics and plan initial UXR session.

## Dates
Goal Date:  

Description: 

Testing Days required: 

## Success Metrics
**TBD**

95% of a group of 20-100 users surveyed - who don't have additional context beyond Status providing a p2p IM capability - using the app for an extended period of time, should answer 'yes' to the question: "Do you trust Status to deliver messages for you?" (and possibly variants of this).

This is fundamentally a soft or qualitative goal. It is thus necessary but not necessarily sufficient, and additional harder numbers might be used as we develop the capability to measure this.

Zero instabug reports within 30 days of alpha release

## Copyright
Copyright and related rights waived via [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

**Comment by rasom** [comment]
proposed scope for the first iteration:
1. Provide better feedback of when messages are or aren't sent (specifically notify clj side when message actually "left" local node). Rethink "sent" status (currently it doesn't mean that message was actually sent, only that it was passed to local node)
2. Disambiguate 'network offline' and 'mail server connection issues' error reporting to user
3. Remove "seen by everyone" from public chat
4. Messages timestamps: design
5. Messages timestamps: dev

**Comment by mandrigin** [comment]
Regarding (1). The relative scope of this task is:
1) make `shh.post` actually return an envelope hash and not a boolean value (see https://web3js.readthedocs.io/en/1.0/web3-shh.html#post)
2) make an API to check if any of the connected whisper peers already have this envelope (see `whisperv6/peer.go`, `known` set).

**Comment by rasom** [comment]
@mandrigin i would prefer to create another method rather then change `ssh.post`, because Dapp/bot developers will rely on official API.

**Comment by oskarth** [comment]
Closing this issue as part of spring cleaning. If this idea is still relevant, please submit a PR per https://github.com/status-im/ideas/#contributing. If you feel closing this issue is a mistake, feel free to re-open.
